#TODO add script for gnu make: https://github.com/Xfennec/progress#how-do-you-build-it-from-source
[source]
git = "https://github.com/Xfennec/progress"
rev = "v0.17"
shallow_clone = true
[build]
template = "custom"
dependencies = [
    "ncursesw",
]
