#TODO camino crate error
[source]
git = "https://github.com/trailofbits/necessist"
[build]
template = "custom"
dependencies = [
    "sqlite3",
    "openssl3",
]
script = """
cookbook_cargo_packages necessist
"""
