[source]
git = "https://github.com/yaml/pyyaml.git"
rev = "6.0.3"
shallow_clone = true

[build]
template = "python"
dev-dependencies = [
    "host:python312",
    "host:python3-setuptools",
    "host:python3-cython",
]

[package]
dependencies = [
    "python312"
]
