#TODO determine minimum dependencies from meson log
[source]
tar = "https://sources.phosh.mobi/releases/phosh-osk-stevia/phosh-osk-stevia-0.56.0.tar.xz"
[build]
template = "meson"
mesonflags = [
    "-Dtests=false",
]
