[source]
git = "https://gitlab.redox-os.org/redox-os/base.git"

[build]
template = "custom"
script = """
cd "${COOKBOOK_SOURCE}" && make install-base \
    SRC_DIR="${COOKBOOK_SOURCE}" SYSROOT="${COOKBOOK_SYSROOT}" \
    LINKER="${GNU_TARGET}-ld" CARGO="${COOKBOOK_CARGO}" \
    BUILD_DIR="${COOKBOOK_BUILD}" DESTDIR="${COOKBOOK_STAGE}"
"""
