[source]
git = "https://github.com/pop-os/icon-theme.git"
shallow_clone = true

[build]
template = "meson"

[[optional-packages]]
name = "cursors"
files = [
    "usr/share/icons/Pop/cursors**",
    "usr/share/icons/Pop/cursor.theme",
]
