#TODO not compiled or tested
#TODO require the rustc-demangle library for rust support: https://github.com/rust-lang/rustc-demangle
[source]
git = "https://invent.kde.org/sdk/heaptrack"
rev = "v1.5.0"
shallow_clone = true
[build]
template = "cmake"
cmakeflags = [
    "-DHEAPTRACK_BUILD_ANALYZE_DEFAULT=OFF",
    "-DHEAPTRACK_BUILD_GUI=OFF",
]
dev-dependencies = ["host:ecm"]
dependencies = [
    "zlib",
    "boost",
    "libunwind",
    "elfutils",
]
