#TODO not compiled or tested
[source]
git = "https://github.com/slint-ui/slint"
shallow_clone = true
[build]
template = "cargo"
cargopackages = [
    "gallery",
    "energy-monitor",
    "carousel",
    "memory",
    "imagefilter",
    "plotter",
    "opengl_underlay",
    "opengl_texture",
    "maps",
    "virtual_keyboard",
    "7guis",
]
