#TODO iroh-quinn-udp crate error
[source]
git = "https://github.com/fishfolk/bones"
shallow_clone = true
[build]
template = "cargo"
cargopackagesprefixed = true
cargopackages = [
    "demo_hello_world",
]
