#TODO not compiled or tested
#TODO discover minimum dependencies from cmake log
# build instructions: https://docs.krita.org/en/untranslatable_pages/building_krita.html#building-on-linux
[source]
git = "https://invent.kde.org/graphics/krita"
branch = "krita/6.0"
shallow_clone = true
[build]
template = "cmake"
cmakeflags = [
    "-DLIMIT_LONG_TESTS=OFF",
    "-DENABLE_UPDATERS=OFF",
]
# dependencies = [
#     "gexiv2",
#     "ffmpeg6",
#     "fftw",
#     "fontconfig",
#     "freetype2",
#     "fribidi",
#     "libgif",
#     "harfbuzz",
#     "liblcms",
#     "libpng",
#     "libtiff",
#     "libwebp",
#     "qt6-base",
#     "qt6-svg",
#     "zlib",
#     "libmypaint",
#     "boost",
#     "libheif",
#     "libjpeg",
#     "libjxl",
#     "kf6-extra-cmake-modules",
#     "kf6-completion",
#     "kf6-config",
#     "kf6-coreaddons",
#     "kf6-crash",
#     "kf6-guiaddons",
#     "kf6-i18n",
#     "kf6-itemviews",
#     "kf6-widgetaddons",
#     "kf6-windowsystem",
#     "mlt",
#     "opencolorio",
#     "openexr",
#     "openjpeg",
#     "sdl2",
#     "libxi",
#     "zlib",
#     "libeigen",
#     "libgsl",
#     "libseexpr-kde",
#     "liblager",
#     "libunibreak",
#     "libxsimd",
#     "libxtl",
# ]
