#TODO not compiled or tested
#TODO discover minimum dependencies from cmake log
# build instructions: https://docs.krita.org/en/untranslatable_pages/building_krita.html#building-on-linux
[source]
git = "https://invent.kde.org/graphics/krita"
rev = "v6.0.2.1"
shallow_clone = true
[build]
template = "cmake"
cmakeflags = [
    "-DLIMIT_LONG_TESTS=OFF",
    "-DENABLE_UPDATERS=OFF",
    "-DBUILD_WITH_QT6=ON",
    "-DALLOW_UNSTABLE=QT6",
]
dependencies = [
     "qt6-qt5compat",
     "qt6-base",
     "qt6-declarative",
     "qt6-svg",
     "kcompletion6",
     "kconfig6",
     "kcoreaddons6",
     "kguiaddons6",
     "ki18n6",
     "kitemviews6",
     "kwidgetsaddons6",
#     "gexiv2",
#     "ffmpeg6",
#     "fftw",
#     "fontconfig",
#     "freetype2",
#     "fribidi",
#     "libgif",
#     "harfbuzz",
#     "liblcms",
#     "libpng",
#     "libtiff",
#     "libwebp",
#     "zlib",
#     "libmypaint",
#     "boost",
#     "libheif",
#     "libjpeg",
#     "libjxl",
#     "mlt",
#     "opencolorio",
#     "openexr",
#     "openjpeg",
#     "sdl2",
#     "libxi",
#     "zlib",
#     "libeigen",
#     "libgsl",
#     "libseexpr-kde",
#     "liblager",
#     "libunibreak",
#     "libxsimd",
#     "libxtl",
]
