#TODO not compiled or tested
#TODO disable udev codepath or translate udev api to redox like freebsd does?
#TODO patch to disable libgbm
# build instructions: https://gitlab.com/mission-center-devs/mission-center#building---native
[source]
git = "https://gitlab.com/mission-center-devs/mission-center"
[build]
template = "meson"
dependencies = [
    "gtk4",
    "libadwaita",
    "libdrm",
    "dbus",
]
