#TODO not compiled or tested
[source]
tar = "https://github.com/teeworlds/teeworlds/releases/download/0.7.5/teeworlds-0.7.5-src.tar.gz"
shallow_clone = true
[build]
template = "cmake"
cmakeflags = [
    "-GNinja",
    "-DDOWNLOAD_GTEST=OFF",
]
dependencies = [
    "sdl2",
    "freetype2",
    "wavpack",
]
