#TODO try to open a configure script in a sub-directory but can't find
[source]
git = "https://github.com/cmus/cmus"
rev = "v2.12.0"
shallow_clone = true
[build]
template = "configure"
dependencies = [
    "ncursesw",
]
