#TODO not compiled or tested
# build instructions: https://cgit.git.savannah.gnu.org/cgit/gcl.git/tree/gcl/INSTALL
[source]
tar = "http://ftpmirror.gnu.org/gcl/gcl-2.7.1.tar.gz"
[build]
template = "configure"
