#TODO fontique crate error
[source]
git = "https://github.com/DioxusLabs/blitz"
shallow_clone = true
[build]
template = "cargo"
cargoexamples = [
    "url",
    "markdown",
]
dependencies = [
    "openssl3",
]
