#TODO add script for cross-compilation: https://vuls.io/docs/en/install-manually.html
#TODO which sql database implementation is needed?
[source]
git = "https://github.com/future-architect/vuls"
rev = "v0.39.2"
shallow_clone = true
[build]
template = "custom"
