[source]
tar = "https://archive.xfce.org/src/xfce/thunar/4.21/thunar-4.21.5.tar.xz"
blake3 = "3e7572c5c4c2621acc8bf743565b727af4b37bbe27bd07ce8a8d8def37a8a8c3"
[build]
dependencies = [
    "atk",
    "cairo",
    "gdk-pixbuf",
    "gettext",
    "glib",
    "gtk3",
    "libice",
    "libnotify",
    "libx11",
    "libxfce4ui",
    "libxfce4util",
    "pango",
    "pcre2",
    "vte",
    "xfconf",
]
dev-dependencies = [
    "libstdcxx"
]
template = "meson"
mesonflags = [
    "-Dpolkit=disabled",
    "-Dgudev=disabled",
    "-Dintrospection=false"
]

[package]
dependencies = [
    "gnome-desktop-schemas"
]
