#TODO build configuration error
#TODO some failling tests
# build instructions: https://github.com/dolphin-emu/dolphin/wiki/Building-for-Linux
[source]
git = "https://github.com/dolphin-emu/dolphin"
rev = "2606"
shallow_clone = true
[build]
template = "cmake"
cmakeflags = [
    "-DENABLE_LTO=ON",
    "-DUSE_UPNP=OFF",
    "-DENABLE_ALSA=OFF",
    "-DENABLE_PULSEAUDIO=OFF",
    "-DENABLE_CUBEB=OFF",
    "-DENABLE_TESTS=OFF",
    "-DENABLE_VULKAN=OFF",
    "-DUSE_DISCORD_PRESENCE=OFF",
    "-DUSE_MGBA=OFF",
    "-DENABLE_AUTOUPDATE=OFF",
    "-DUSE_RETRO_ACHIEVEMENTS=OFF",
    "=DENABLE_ANALYTICS=OFF",
    "-DENCODE_FRAMEDUMPS=OFF",
    "-DENABLE_LLVM=OFF",
    "-DENABLE_QT=OFF",
]
dependencies = [
    "libhidapi",
    "mbedtls",
    "sdl3",
    "libusb",
    "lz4",
    "minizip-ng",
    "zlib",
    "zstd",
    "xxhash",
    "bzip2",
    "libenet",
    "pugixml",
    "glslang",
    "libfmt",
]
