[source]
git = "https://github.com/pop-os/cosmic-text.git"
branch = "main"

[build]
template = "custom"
script = """
DYNAMIC_INIT
COOKBOOK_CARGO_FLAGS=() # remove --locked
COOKBOOK_CARGO_PATH=examples/editor cookbook_cargo_build
"""
