#TODO quinn-udp crate error
#TODO verify if udev is optional
[source]
git = "https://gitlab.com/veloren/veloren"
shallow_clone = true
[build]
template = "cargo"
cargopackages = ["veloren-client"]
#dependencies = [
    #"glib",
    #"cairo",
    #"pango",
    #"atk",
    #"gdk-pixbuf",
    #"gtk3",
    #"mesa",
#]
