# TODO iana-time-zone os detection (https://gitlab.redox-os.org/redox-os/redox/-/work_items/1838)
[source]
git = "https://github.com/wasmi-labs/wasmi"
[build]
template = "custom"
script = """
cookbook_cargo_packages wasmi_cli
"""
