[package]
dependencies = [
    "thunar",
    "tumbler",
    "xfconf",
    "xfdesktop",
    "xfce4-appfinder",
    "xfce4-session",
    "xfce4-panel",
    "xfce4-settings",
    "xfwm4",
]
description = "Minimal components for X11-based XFCE4 desktop"
