#TODO not compiled or tested
#TODO enable "backend_winit" and "renderer_pixman" feature flags from smithay
# configuration: https://github.com/YaLTeR/niri#installation
[source]
git = "https://github.com/YaLTeR/niri"
shallow_clone = true
[build]
template = "custom"
dependencies = [
    "libwayland",
]
script = """
DYNAMIC_INIT
cookbook_cargo --no-default-features
mkdir -pv "${COOKBOOK_STAGE}"/usr/bin
mkdir -pv "${COOKBOOK_STAGE}"/usr/share/wayland-sessions
mkdir -pv "${COOKBOOK_STAGE}"/usr/share/xdg-desktop-portal
cp -rv "${COOKBOOK_SOURCE}"/resources/niri-session "${COOKBOOK_STAGE}"/usr/bin
cp -rv "${COOKBOOK_SOURCE}"/resources/niri.desktop "${COOKBOOK_STAGE}"/usr/share/wayland-sessions
cp -rv "${COOKBOOK_SOURCE}"/resources/niri-portals.conf "${COOKBOOK_STAGE}"/usr/share/xdg-desktop-portal
"""
