#TODO can't find boost
#TODO make sdl2-sys crate use sdl2 recipe?
[source]
git = "https://github.com/hikari-no-yume/touchHLE"
shallow_clone = true
[build]
template = "cargo"
dependencies = [
    "boost"
    "sdl2",
]
