#TODO make gtk3 work
[source]
git = "https://github.com/elkowar/eww"
shallow_clone = true
[build]
template = "cargo"
cargopackages = ["eww"]
dependencies = [
    "gtk3",
    "pango",
    "cairo",
    "gdk-pixbuf",
    "glib",
]
