[source]
# git = "https://gitlab.redox-os.org/redox-os/redoxfs.git"
git = "https://gitlab.redox-os.org/Ibuki.O/redoxfs.git"
# branch = "scheme_root_fd"
branch = "unlinkat"

[build]
template = "custom"
script = """
# Must be statically linked
cookbook_cargo
"""
