#TODO not compiled or tested
[source]
git = "https://github.com/ratatui/ratatui"
branch = "latest"
shallow_clone = true
[build]
template = "cargo"
cargoflags = ["--no-default-features --features termion"]
cargopackages = [
    "async-github",
    "calendar-explorer",
    "canvas",
    "chart",
    "color-explorer",
    "colors-rgb",
    "demo",
    "demo2",
    "hyperlink",
    "hello-world",
    "inline",
    "modifiers",
    "mouse-drawing",
    "simple",
    "panic",
    "popup",
    "scrollbar",
    "table",
    "todo-list",
    "tracing",
    "user-input",
]
cargoexamples = [
    "block",
    "calendar",
    "canvas",
    "chart",
    "logo",
    "scrollbar",
    "sparkline",
    "tabs",
]
