.TH "SDL_CDStop" "3" "Tue 11 Sep 2001, 22:59" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_CDStop \- Stops a CDROM
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBint \fBSDL_CDStop\fP\fR(\fBSDL_CD *cdrom\fR);
.SH "DESCRIPTION"
.PP
Stops play on the given \fBcdrom\fR\&.
.SH "RETURN VALUE"
.PP
Returns \fB0\fR on success, or \fB-1\fR on an error\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_CDPlay\fP\fR,
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 22:59
