.TH "SDL_WM_ToggleFullScreen" "3" "Tue 11 Sep 2001, 23:02" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_WM_ToggleFullScreen \- Toggles fullscreen mode
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBint \fBSDL_WM_ToggleFullScreen\fP\fR(\fBSDL_Surface *surface\fR);
.SH "DESCRIPTION"
.PP
Toggles the application between windowed and fullscreen mode, if supported\&. (X11 is the only target currently supported, BeOS support is experimental)\&.
.SH "RETURN VALUE"
.PP
Returns \fB0\fR on failure or \fB1\fR on success\&.
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:02
