.TH "SDL_GetEventFilter" "3" "Tue 11 Sep 2001, 22:59" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_GetEventFilter \- Retrieves a pointer to he event filter
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBSDL_EventFilter \fBSDL_GetEventFilter\fP\fR(\fBvoid\fR);
.SH "DESCRIPTION"
.PP
This function retrieces a pointer to the event filter that was previously set using \fI\fBSDL_SetEventFilter\fP\fR\&. An SDL_EventFilter function is defined as: 
.PP
.nf
\f(CWtypedef int (*SDL_EventFilter)(const SDL_Event *event);\fR
.fi
.PP
.SH "RETURN VALUE"
.PP
Returns a pointer to the event filter or \fBNULL\fP if no filter has been set\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_Event\fR\fR, \fI\fBSDL_SetEventFilter\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 22:59
