.TH "SDL_mutexV" "3" "Tue 11 Sep 2001, 23:01" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_mutexV \- Unlock a mutex
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
#include "SDL_thread\&.h"
.sp
\fBint \fBSDL_mutexV\fP\fR(\fBSDL_mutex *mutex\fR);
.SH "DESCRIPTION"
.PP
Unlocks the \fBmutex\fR, which was previously created with \fI\fBSDL_CreateMutex\fP\fR\&. Returns \fB0\fR on success, or \fB-1\fR on an error\&.
.PP
SDL also defines a macro \fB#define SDL_UnlockMutex(m) SDL_mutexV(m)\fP\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_CreateMutex\fP\fR, \fI\fBSDL_mutexP\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:01
