.TH "SDL_JoystickIndex" "3" "Tue 11 Sep 2001, 23:00" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_JoystickIndex \- Get the index of an SDL_Joystick\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBint \fBSDL_JoystickIndex\fP\fR(\fBSDL_Joystick *joystick\fR);
.SH "DESCRIPTION"
.PP
Returns the index of a given \fBSDL_Joystick\fR structure\&.
.SH "RETURN VALUE"
.PP
Index number of the joystick\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_JoystickOpen\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:00
