.TH "SDL_ConvertSurface" "3" "Tue 11 Sep 2001, 23:01" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_ConvertSurface \- Converts a surface to the same format as another surface\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL/SDL\&.h"
.sp
\fBSDL_Surface *\fBSDL_ConvertSurface\fP\fR(\fBSDL_Surface *src, SDL_PixelFormat *fmt, Uint32 flags\fR);
.SH "DESCRIPTION"
.PP
Creates a new surface of the specified format, and then copies and maps the given surface to it\&. If this function fails, it returns \fBNULL\fP\&.
.PP
The \fBflags\fR parameter is passed to \fI\fBSDL_CreateRGBSurface\fP\fR and has those semantics\&.
.PP
This function is used internally by \fI\fBSDL_DisplayFormat\fP\fR\&.
.PP
This function can only be called after SDL_Init\&.
.SH "RETURN VALUE"
.PP
Returns either a pointer to the new surface, or \fBNULL\fP on error\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_CreateRGBSurface\fP\fR, \fI\fBSDL_DisplayFormat\fP\fR, \fI\fBSDL_PixelFormat\fR\fR, \fI\fBSDL_Surface\fR\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:01
