.TH "SDL_ThreadID" "3" "Tue 11 Sep 2001, 23:00" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_ThreadID \- Get the 32-bit thread identifier for the current thread\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
#include "SDL_thread\&.h"
.sp
\fBUint32 \fBSDL_ThreadID\fP\fR(\fBvoid\fR)
.SH "DESCRIPTION"
.PP
Get the 32-bit thread identifier for the current thread\&.
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:00
