.TH "SDL_UnlockSurface" "3" "Tue 11 Sep 2001, 23:01" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_UnlockSurface \- Unlocks a previously locked surface\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBvoid \fBSDL_UnlockSurface\fP\fR(\fBSDL_Surface *surface\fR);
.SH "DESCRIPTION"
.PP
Surfaces that were previously locked using \fBSDL_LockSurface\fP must be unlocked with \fBSDL_UnlockSurface\fP\&. Surfaces should be unlocked as soon as possible\&.
.PP
It should be noted that since 1\&.1\&.8, surface locks are recursive\&. See \fI\fBSDL_LockSurface\fP\fR\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_LockSurface\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:01
