.TH "SDL_CDResume" "3" "Tue 11 Sep 2001, 22:58" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_CDResume \- Resumes a CDROM
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBint \fBSDL_CDResume\fP\fR(\fBSDL_CD *cdrom\fR);
.SH "DESCRIPTION"
.PP
Resumes play on the given \fBcdrom\fR\&.
.SH "RETURN VALUE"
.PP
Returns \fB0\fR on success, or \fB-1\fR on an error\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_CDPlay\fP\fR, \fI\fBSDL_CDPause\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 22:58
