.TH "SDL_WM_GetCaption" "3" "Tue 11 Sep 2001, 23:01" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_WM_GetCaption \- Gets the window title and icon name\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBvoid \fBSDL_WM_GetCaption\fP\fR(\fBchar **title, char **icon\fR);
.SH "DESCRIPTION"
.PP
Set pointers to the window \fBtitle\fR and \fBicon\fR name\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_WM_SetCaption\fP\fR, \fI\fBSDL_WM_SetIcon\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:01
