.TH "SDL_EnableUNICODE" "3" "Tue 11 Sep 2001, 22:59" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_EnableUNICODE \- Enable UNICODE translation
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBint \fBSDL_EnableUNICODE\fP\fR(\fBint enable\fR);
.SH "DESCRIPTION"
.PP
Enables/Disables Unicode keyboard translation\&.
.PP
To obtain the character codes corresponding to received keyboard events, Unicode translation must first be turned on using this function\&. The translation incurs a slight overhead for each keyboard event and is therefore disabled by default\&. For each subsequently received key down event, the \fBunicode\fR member of the \fI\fBSDL_keysym\fR\fR structure will then contain the corresponding character code, or zero for keysyms that do not correspond to any character code\&.
.PP
A value of 1 for \fBenable\fR enables Unicode translation; 0 disables it, and -1 leaves it unchanged (useful for querying the current translation mode)\&.
.PP
Note that only key press events will be translated, not release events\&.
.SH "RETURN VALUE"
.PP
Returns the previous translation mode (\fB0\fR or \fB1\fR)\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_keysym\fR\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 22:59
