.TH "SDL_NumJoysticks" "3" "Tue 11 Sep 2001, 23:00" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_NumJoysticks \- Count available joysticks\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBint \fBSDL_NumJoysticks\fP\fR(\fBvoid\fR);
.SH "DESCRIPTION"
.PP
Counts the number of joysticks attached to the system\&.
.SH "RETURN VALUE"
.PP
Returns the number of attached joysticks
.SH "SEE ALSO"
.PP
\fI\fBSDL_JoystickName\fP\fR, \fI\fBSDL_JoystickOpen\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:00
