.TH "SDL_WM_GrabInput" "3" "Tue 11 Sep 2001, 23:01" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_WM_GrabInput \- Grabs mouse and keyboard input\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBSDL_GrabMode \fBSDL_WM_GrabInput\fP\fR(\fBSDL_GrabMode mode\fR);
.SH "DESCRIPTION"
.PP
Grabbing means that the mouse is confined to the application window, and nearly all keyboard input is passed directly to the application, and not interpreted by a window manager, if any\&.
.PP
When \fBmode\fR is \fBSDL_GRAB_QUERY\fP the grab mode is not changed, but the current grab mode is returned\&.
.PP
.PP
.nf
\f(CWtypedef enum {
  SDL_GRAB_QUERY,
  SDL_GRAB_OFF,
  SDL_GRAB_ON
} SDL_GrabMode;\fR
.fi
.PP
 
.SH "RETURN VALUE"
.PP
The current/new \fBSDL_GrabMode\fR\&.
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:01
