.TH "SDL_GetCursor" "3" "Tue 11 Sep 2001, 23:01" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_GetCursor \- Get the currently active mouse cursor\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBSDL_Cursor *\fBSDL_GetCursor\fP\fR(\fBvoid\fR);
.SH "DESCRIPTION"
.PP
Returns the currently active mouse cursor\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_SetCursor\fP\fR, \fI\fBSDL_CreateCursor\fP\fR, \fI\fBSDL_ShowCursor\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:01
