.TH "SDL_GetRGBA" "3" "Tue 11 Sep 2001, 23:01" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_GetRGBA \- Get RGBA values from a pixel in the specified pixel format\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBvoid \fBSDL_GetRGBA\fP\fR(\fBUint32 pixel, SDL_PixelFormat *fmt, Uint8 *r, Uint8 *g, Uint8 *b, Uint8 *a\fR);
.SH "DESCRIPTION"
.PP
Get RGBA component values from a pixel stored in the specified pixel format\&.
.PP
This function uses the entire 8-bit [0\&.\&.255] range when converting color components from pixel formats with less than 8-bits per RGB component (e\&.g\&., a completely white pixel in 16-bit RGB565 format would return [0xff, 0xff, 0xff] not [0xf8, 0xfc, 0xf8])\&.
.PP
If the surface has no alpha component, the alpha will be returned as 0xff (100% opaque)\&.
.SH "SEE ALSO"
.PP
\fISDL_GetRGB\fR, \fISDL_MapRGB\fR, \fISDL_MapRGBA\fR, \fISDL_PixelFormat\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:01
