.TH "SDL_GetGamma" "3" "Tue 11 Sep 2001, 23:01" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_GetGamma \- Gets the gamma of the display
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBint \fBSDL_GetGamma\fP\fR(\fBfloat *red, float *green, float *blue\fR);
.SH "DESCRIPTION"
.PP
Gets the color gamma of the display\&. The gamma value for each color component will be place in the parameters \fBred\fR, \fBgreen\fR and \fBblue\fR\&. The values can range from 0\&.1 to 10\&.
.PP
.RS
\fBNote:  
.PP
This function currently only works on XFreee 4\&.0 and up\&.
.RE
.SH "SEE ALSO"
.PP
\fI\fBSDL_SetGamma\fP\fR, \fI\fBSDL_SetVideoMode\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:01
