.TH "SDL_Rect" "3" "Tue 11 Sep 2001, 23:01" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_Rect \- Defines a rectangular area
.SH "STRUCTURE DEFINITION"
.PP
.nf
\f(CWtypedef struct{
  Sint16 x, y;
  Uint16 w, h;
} SDL_Rect;\fR
.fi
.PP
.SH "STRUCTURE DATA"
.TP 20
\fBx, y\fR
Position of the upper-left corner of the rectangle
.TP 20
\fBw, h\fR
The width and height of the rectangle
.SH "DESCRIPTION"
.PP
A \fBSDL_Rect\fR defines a rectangular area of pixels\&. It is used by \fI\fBSDL_BlitSurface\fP\fR to define blitting regions and by several other video functions\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_BlitSurface\fP\fR, \fI\fBSDL_UpdateRect\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:01
