.TH "SDL_CreateCond" "3" "Tue 11 Sep 2001, 23:00" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_CreateCond \- Create a condition variable
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
#include "SDL_thread\&.h"
.sp
\fBSDL_cond *\fBSDL_CreateCond\fP\fR(\fBvoid\fR);
.SH "DESCRIPTION"
.PP
Creates a condition variable\&.
.SH "EXAMPLES"
.PP
.nf
\f(CWSDL_cond *cond;

cond=SDL_CreateCond();
\&.
\&.
/* Do stuff */

\&.
\&.
SDL_DestroyCond(cond);\fR
.fi
.PP
.SH "SEE ALSO"
.PP
\fI\fBSDL_DestroyCond\fP\fR, \fI\fBSDL_CondWait\fP\fR, \fI\fBSDL_CondSignal\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:00
