.TH "SDL_CD" "3" "Tue 11 Sep 2001, 22:58" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_CD \- CDROM Drive Information
.SH "STRUCTURE DEFINITION"
.PP
.nf
\f(CWtypedef struct{
  int id;
  CDstatus status;
  int numtracks;
  int cur_track;
  int cur_frame;
  SDL_CDtrack track[SDL_MAX_TRACKS+1];
} SDL_CD;\fR
.fi
.PP
.SH "STRUCTURE DATA"
.TP 20
\fBid\fR
Private drive identifier
.TP 20
\fBstatus\fR
Drive \fIstatus\fR
.TP 20
\fBnumtracks\fR
Number of tracks on the CD
.TP 20
\fBcur_track\fR
Current track
.TP 20
\fBcur_frame\fR
Current frame offset within the track
.TP 20
\fBtrack\fR[SDL_MAX_TRACKS+1]
Array of track descriptions\&. (see \fI\fBSDL_CDtrack\fR\fR)
.SH "DESCRIPTION"
.PP
An \fBSDL_CD\fR structure is returned by \fI\fBSDL_CDOpen\fP\fR\&. It represents an opened CDROM device and stores information on the layout of the tracks on the disc\&.
.PP
A frame is the base data unit of a CD\&. \fBCD_FPS\fP frames is equal to 1 second of music\&. SDL provides two macros for converting between time and frames: \fBFRAMES_TO_MSF(f, M,S,F)\fP and \fBMSF_TO_FRAMES\fP\&.
.SH "EXAMPLES"
.PP
.nf
\f(CWint min, sec, frame;
int frame_offset;

FRAMES_TO_MSF(cdrom->cur_frame, &min, &sec, &frame);
printf("Current Position: %d minutes, %d seconds, %d frames
", min, sec, frame);

frame_offset=MSF_TO_FRAMES(min, sec, frame);\fR
.fi
.PP
.SH "SEE ALSO"
.PP
\fI\fBSDL_CDOpen\fP\fR, \fI\fBSDL_CDtrack\fR\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 22:58
