.TH "SDL_DestroyCond" "3" "Tue 11 Sep 2001, 23:00" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_DestroyCond \- Destroy a condition variable
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
#include "SDL_thread\&.h"
.sp
\fBvoid \fBSDL_DestroyCond\fP\fR(\fBSDL_cond *cond\fR);
.SH "DESCRIPTION"
.PP
Destroys a condition variable\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_CreateCond\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:00
