.TH "SDL_SetModState" "3" "Tue 11 Sep 2001, 23:00" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_SetModState \- Set the current key modifier state
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBvoid \fBSDL_SetModState\fP\fR(\fBSDLMod modstate\fR);
.SH "DESCRIPTION"
.PP
The inverse of \fI\fBSDL_GetModState\fP\fR, \fBSDL_SetModState\fP allows you to impose modifier key states on your application\&.
.PP
Simply pass your desired modifier states into \fBmodstate\fR\&. This value my be a logical OR\&'d combination of the following:
.PP
.nf
\f(CWtypedef enum {
  KMOD_NONE  = 0x0000,
  KMOD_LSHIFT= 0x0001,
  KMOD_RSHIFT= 0x0002,
  KMOD_LCTRL = 0x0040,
  KMOD_RCTRL = 0x0080,
  KMOD_LALT  = 0x0100,
  KMOD_RALT  = 0x0200,
  KMOD_LMETA = 0x0400,
  KMOD_RMETA = 0x0800,
  KMOD_NUM   = 0x1000,
  KMOD_CAPS  = 0x2000,
  KMOD_MODE  = 0x4000,
} SDLMod;\fR
.fi
.PP
.SH "SEE ALSO"
.PP
\fI\fBSDL_GetModState\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:00
