.TH "SDL_LoadBMP" "3" "Tue 11 Sep 2001, 23:01" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_LoadBMP \- Load a Windows BMP file into an SDL_Surface\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBSDL_Surface *\fBSDL_LoadBMP\fP\fR(\fBconst char *file\fR);
.SH "DESCRIPTION"
.PP
Loads a surface from a named Windows BMP file\&.
.SH "RETURN VALUE"
.PP
Returns the new surface, or \fBNULL\fP if there was an error\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_SaveBMP\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:01
