.TH "SDL_EnableKeyRepeat" "3" "Tue 11 Sep 2001, 22:59" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_EnableKeyRepeat \- Set keyboard repeat rate\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBint \fBSDL_EnableKeyRepeat\fP\fR(\fBint delay, int interval\fR);
.SH "DESCRIPTION"
.PP
Enables or disables the keyboard repeat rate\&. \fBdelay\fR specifies how long the key must be pressed before it begins repeating, it then repeats at the speed specified by \fBinterval\fR\&. Both \fBdelay\fR and \fBinterval\fR are expressed in milliseconds\&.
.PP
Setting \fBdelay\fR to 0 disables key repeating completely\&. Good default values are \fBSDL_DEFAULT_REPEAT_DELAY\fP and \fISDL_DEFAULT_REPEAT_INTERVAL\fP\&.
.SH "RETURN VALUE"
.PP
Returns \fB0\fR on success and \fB-1\fR on failure\&.
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 22:59
