.TH "SDL_GetError" "3" "Tue 11 Sep 2001, 23:00" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_GetError \- Get SDL error string
.SH "SYNOPSIS"
.PP
\fB#include "SDL/SDL\&.h"
.sp
\fBchar *\fBSDL_GetError\fP\fR(\fBvoid\fR);
.SH "DESCRIPTION"
.PP
\fBSDL_GetError\fP returns a NULL terminated string containing information about the last internal SDL error\&.
.SH "RETURN VALUE"
.PP
\fBSDL_GetError\fP returns a string containing the last error\&.
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:00
