#TODO not compiled or tested yet
# build instructions: https://github.com/devmiyax/yabause/blob/master/yabause/README.LIN#L77
[source]
git = "https://github.com/devmiyax/yabause"
rev = "71c973f92966d33de464c1ba4dac1953af6ec462"
shallow_clone = true
[build]
template = "custom"
dependencies = [
    "gtk2",
    "sdl2",
    "mesa",
    "gtkglext",
]
script = """
DYNAMIC_INIT
COOKBOOK_SOURCE="${COOKBOOK_SOURCE}/yabause"
cookbook_cmake
"""
