#TODO not compiled or tested
#TODO build libwebrtc from source: https://github.com/MaikBuse/gosuto#voip--prebuilt-libwebrtc
[source]
git = "https://github.com/MaikBuse/gosuto"
shallow_clone = true
[build]
template = "cargo"
