#TODO ahash crate error
[source]
git = "https://github.com/tesselode/kira-examples"
shallow_clone = true
[build]
template = "cargo"
cargopackagesprefixed = true
cargopackages = [
    "dynamic-music",
    "ghost-noise",
    "metronome",
    "score-counter",
    "spatial-audio",
    "simple-sound-playback",
]
