#TODO compiled but not tested
[source]
git = "https://github.com/isc-projects/bind9"
# last version before ipv6 being mandatory
rev = "v9.12.3"
patches = [
    "redox.patch"
]
shallow_clone = true

[build]
template = "custom"
dependencies = [
    "openssl3",
    "liburcu",
    "libuv",
    "nghttp2", # DoH support
    #"jemalloc", # enable to improve performance
]
script = """
DYNAMIC_INIT
export BUILD_CC="$CC_WRAPPER gcc"
COOKBOOK_CONFIGURE_FLAGS+=(
    --without-python
    --with-openssl="$COOKBOOK_SYSROOT"
    --with-libxml2=no
    --with-randomdev=/dev/urandom
    --with-ecdsa=yes
    --with-gost=yes
    --with-eddsa=yes
    --enable-epoll
    --disable-ipv6
)
cookbook_configure
"""
