#TODO update nix crate version
#TODO make it use sdl3 recipe
[source]
git = "https://github.com/gopher64/gopher64"
shallow_clone = true
[build]
template = "cargo"
dependencies = [
    "sdl3",
    "libwayland",
]
