#TODO not compiled or tested
# build instructions: https://github.com/SpadesX/SpadesX#installation
[source]
git = "https://github.com/SpadesX/SpadesX"
shallow_clone = true
[build]
template = "cmake"
dependencies = [
    "readline",
    "zlib",
    "json-c",
]
