#TODO camino crate error
[source]
git = "https://github.com/rust-secure-code/cargo-geiger"
shallow_clone = true
[build]
template = "custom"
dependencies = [
    "openssl3",
]
script = """
DYNAMIC_INIT
export OPENSSL_DIR="${COOKBOOK_SYSROOT}"
cookbook_cargo_packages cargo-geiger
"""
