#TODO not compiled or tested
# build instructions: https://github.com/openocd-org/openocd/#building-openocd
[source]
tar = "https://sourceforge.net/projects/openocd/files/openocd/0.12.0/openocd-0.12.0.tar.bz2/download"
[build]
template = "configure"
dependencies = [
    "jimtcl",
    #"libusb",
    #"libftdi",
]
