[source]
tar = "https://archive.xfce.org/src/xfce/xfdesktop/4.20/xfdesktop-4.20.2.tar.bz2"
blake3 = "b263f84181023186df1a37e2b2b4a2b61eb63d8f27862c4fbbd5fc4c563d7e0e"
[build]
dependencies = [
    "atk",
    "cairo",
    "expat",
    "fontconfig",
    "freetype2",
    "fribidi",
    "garcon",
    "gdk-pixbuf",
    "gettext",
    "glib",
    "gtk3",
    "harfbuzz",
    "libepoxy",
    "libffi",
    "libiconv",
    "libjpeg",
    "libpng",
    "libpthread-stubs",
    "libsm",
    "libnotify",
    "libwnck3",
    "libx11",
    "libxau",
    "libxcb",
    "libxext",
    "libxfce4ui",
    "libxfce4util",
    "libxfce4windowing",
    "libxfixes",
    "libxft",
    "libxi",
    "libxrandr",
    "libxrender",
    "libxxf86vm",
    "mesa-x11",
    "pango",
    "pcre2",
    "pixman",
    "shared-mime-info",
    "x11proto",
    "vte",
    "xfconf",
    "zlib",
    "libexo",
    "libyaml",
]
template = "meson"
mesonflags = [
]
