# XXX: Do not distribute https://github.com/k4zmu2a/SpaceCadetPinball/issues/1
[source]
git = "https://github.com/k4zmu2a/SpaceCadetPinball.git"
rev = "f760f34e5eb49c69d584921c0f3e251a59c62078"
patches = [ "redox.patch" ]

[build]
template = "custom"
dependencies = [
    "libogg",
    "liborbital",
    "libvorbis",
    "mesa",
    "sdl2",
    "sdl2-mixer",
    "zlib",
]
script = """
DYNAMIC_INIT
cookbook_cmake
"""
