#TODO compile and test
#TODO make it use libvterm recipe
[source]
git = "https://github.com/palomena/sdlterm"
rev = "8c121d26f65cdb2225ddf3f858c70b4c89d65fa6"
shallow_clone = true
[build]
template = "custom"
dependencies = [
    "sdl2",
    "sdl2-ttf",
    "sdl2-image",
    #"libvterm",
]
script = """
rsync -av --delete "${COOKBOOK_SOURCE}/" ./
DYNAMIC_INIT
"${COOKBOOK_MAKE}" -j "${COOKBOOK_MAKE_JOBS}"
"${COOKBOOK_MAKE}" install DESTDIR="${COOKBOOK_STAGE}/usr"
"""
