#TODO not compiled or tested
#TODO discover minimum dependencies from meson log
[source]
git = "https://github.com/hughsie/colord"
rev = "1.4.8"
shallow_clone = true
[build]
template = "meson"
mesonflags = [
    "-Dsystemd=false",
    "-Dudev-rules=false",
    "-Dintrospection=false",
    "-Dtests=false",
    "-Ddocs=false",
    "-Dman=false",
]
