#TODO promote
[source]
git = "https://github.com/FGRibreau/spinners"
rev = "f4aa1ab"
shallow_clone = true
[build]
template = "cargo"
cargoexamples = [
    "cycle",
    "simple",
    "stop_persist",
    "stop_symbol",
    "timer",
]
