#TODO not compiled or tested
#TODO discover minimum dependencies from meson log
[source]
git = "https://github.com/sepehr-rs/Sudoku"
rev = "v1.6.1"
shallow_clone = true
[build]
template = "meson"
[package]
dependencies = [
    "python312"
]
