# TODO region crate error (https://gitlab.redox-os.org/redox-os/redox/-/work_items/1837)
[source]
git = "https://github.com/wasmerio/wasmer"
[build]
template = "custom"
script = """
cookbook_cargo_packages wasmer-cli
"""
