#TODO add script for proper packaging: https://docs.angr.io/en/latest/getting-started/installing.html
[source]
git = "https://github.com/angr/angr"
rev = "v9.2.221"
shallow_clone = true
[build]
template = "custom"
script = """
mkdir -pv "${COOKBOOK_STAGE}/home/user/angr"
cp -rv "${COOKBOOK_SOURCE}"/* "${COOKBOOK_STAGE}/home/user/angr"
"""
[package]
dependencies = [
    "python312",
]
