#TODO instructions https://github.com/bluedragon1221/minlinux2
[build]
template = "custom"
dev-dependencies = [
    "busybox",
    "host:cpio",
]
script = """
mkdir -p initfiles "$COOKBOOK_STAGE/boot"
rsync -a --delete "${COOKBOOK_SYSROOT}/" ./initfiles/
mkdir -p initfiles/{dev,proc,sys,tmp,run,mnt}
pushd initfiles/bin
rm -f su
cp busybox su && chmod +s su
popd

cp -r "${COOKBOOK_RECIPE}/etc" initfiles/
rm -f initfiles/sbin/init
cp -v "${COOKBOOK_RECIPE}/init" initfiles/sbin/init
chmod +x initfiles/sbin/init
pushd initfiles
find . | cpio -o -H newc --owner=+0:+0 > ../init.cpio
popd

cp init.cpio "$COOKBOOK_STAGE/boot"
"""
