#TODO instructions https://github.com/bluedragon1221/minlinux2
[build]
template = "custom"
dev-dependencies = [
    "busybox"
]
script = """
mkdir -p initfiles
rsync -a --delete "${COOKBOOK_SYSROOT}/" ./initfiles/
pushd initfiles/bin
rm su
cp busybox su && chmod +s su
popd

cp -r "${COOKBOOK_RECIPE}/etc" initfiles/
pushd initfiles
find . | cpio -o -H newc --owner=+0:+0 > ../init.cpio
popd

cp init.cpio "$COOKBOOK_STAGE/"
"""
