.TH "SDL_KillThread" "3" "Tue 11 Sep 2001, 23:00" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_KillThread \- Gracelessly terminates the thread\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
#include "SDL_thread\&.h"
.sp
\fBvoid \fBSDL_KillThread\fP\fR(\fBSDL_Thread *thread\fR);
.SH "DESCRIPTION"
.PP
\fBSDL_KillThread\fP gracelessly terminates the thread associated with \fBthread\fR\&. If possible, you should use some other form of IPC to signal the thread to quit\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_CreateThread\fP\fR, \fI\fBSDL_WaitThread\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:00
