.TH "SDL_PollEvent" "3" "Tue 11 Sep 2001, 22:59" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_PollEvent \- Polls for currently pending events\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBint \fBSDL_PollEvent\fP\fR(\fBSDL_Event *event\fR);
.SH "DESCRIPTION"
.PP
Polls for currently pending events, and returns \fB1\fR if there are any pending events, or \fB0\fR if there are none available\&. 
.PP
If \fBevent\fR is not \fBNULL\fP, the next event is removed from the queue and stored in that area\&.
.SH "EXAMPLES"
.PP
.PP
.nf
\f(CWSDL_Event event; /* Event structure */

\&.
\&.
\&.
/* Check for events */
while(SDL_PollEvent(&event)){  /* Loop until there are no events left on the queue */
  switch(event\&.type){  /* Process the appropiate event type */
    case SDL_KEYDOWN:  /* Handle a KEYDOWN event */         
      printf("Oh! Key press
");
      break;
    case SDL_MOUSEMOTION:
      \&.
      \&.
      \&.
    default: /* Report an unhandled event */
      printf("I don\&'t know what this event is!
");
  }
}\fR
.fi
.PP
.SH "SEE ALSO"
.PP
\fI\fBSDL_Event\fR\fR, \fI\fBSDL_WaitEvent\fP\fR, \fI\fBSDL_PeepEvents\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 22:59
