.TH "SDL_mutexP" "3" "Tue 11 Sep 2001, 23:01" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_mutexP \- Lock a mutex
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
#include "SDL_thread\&.h"
.sp
\fBint \fBSDL_mutexP\fP\fR(\fBSDL_mutex *mutex\fR);
.SH "DESCRIPTION"
.PP
Locks the \fBmutex\fR, which was previously created with \fI\fBSDL_CreateMutex\fP\fR\&. If the mutex is already locked then \fBSDL_mutexP\fP will not return until it is \fIunlocked\fR\&. Returns \fB0\fR on success, or \fB-1\fR on an error\&.
.PP
SDL also defines a macro \fB#define SDL_LockMutex(m) SDL_mutexP(m)\fP\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_CreateMutex\fP\fR, \fI\fBSDL_mutexV\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:01
