.TH "SDL_GetRelativeMouseState" "3" "Tue 11 Sep 2001, 22:59" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_GetRelativeMouseState \- Retrieve the current state of the mouse
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBUint8 \fBSDL_GetRelativeMouseState\fP\fR(\fBint *x, int *y\fR);
.SH "DESCRIPTION"
.PP
The current button state is returned as a button bitmask, which can be tested using the \fBSDL_BUTTON(X)\fP macros, and \fBx\fR and \fBy\fR are set to the change in the mouse position since the last call to \fBSDL_GetRelativeMouseState\fP or since event initialization\&. You can pass \fBNULL\fP for either \fBx\fR or \fBy\fR\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_GetMouseState\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 22:59
