.TH "SDL_GetThreadID" "3" "Tue 11 Sep 2001, 23:00" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_GetThreadID \- Get the SDL thread ID of a SDL_Thread
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
#include "SDL_thread\&.h"
.sp
\fBUint32 \fBSDL_GetThreadID\fP\fR(\fBSDL_Thread *thread\fR);
.SH "DESCRIPTION"
.PP
Returns the ID of a \fBSDL_Thread\fR created by \fISDL_CreateThread\fR\&.
.SH "SEE ALSO"
.PP
\fISDL_CreateThread\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:00
