.TH "SDL_FreeWAV" "3" "Tue 11 Sep 2001, 22:58" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_FreeWAV \- Frees previously opened WAV data
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBvoid \fBSDL_FreeWAV\fP\fR(\fBUint8 *audio_buf\fR);
.SH "DESCRIPTION"
.PP
After a WAVE file has been opened with \fI\fBSDL_LoadWAV\fP\fR its data can eventually be freed with \fBSDL_FreeWAV\fP\&. \fBaudio_buf\fR is a pointer to the buffer created by \fBSDL_LoadWAV\fP\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_LoadWAV\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 22:58
