.TH "SDL_CDtrack" "3" "Tue 11 Sep 2001, 22:59" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_CDtrack \- CD Track Information Structure
.SH "STRUCTURE DEFINITION"
.PP
.nf
\f(CWtypedef struct{
  Uint8 id;
  Uint8 type;
  Uint32 length;
  Uint32 offset;
} SDL_CDtrack;\fR
.fi
.PP
.SH "STRUCTURE DATA"
.TP 20
\fBid\fR
Track number (0-99)
.TP 20
\fBtype\fR
\fBSDL_AUDIO_TRACK\fP or \fBSDL_DATA_TRACK\fP
.TP 20
\fBlength\fR
Length, in frames, of this track
.TP 20
\fBoffset\fR
Frame offset to the beginning of this track
.SH "DESCRIPTION"
.PP
\fBSDL_CDtrack\fR stores data on each track on a CD, its fields should be pretty self explainatory\&. It is a member a the \fI\fBSDL_CD\fR\fR structure\&.
.PP
.RS
\fBNote:  
.PP
Frames can be converted to standard timings\&. There are \fBCD_FPS\fP frames per second, so \fBSDL_CDtrack\fR\&.\fBlength\fR/\fBCD_FPS\fP=length_in_seconds\&.
.RE
.SH "SEE ALSO"
.PP
\fI\fBSDL_CD\fR\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 22:59
