.TH "SDL_EventState" "3" "Tue 11 Sep 2001, 22:59" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_EventState \- This function allows you to set the state of processing certain events\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBUint8 \fBSDL_EventState\fP\fR(\fBUint8 type, int state\fR);
.SH "DESCRIPTION"
.PP
This function allows you to set the state of processing certain event \fBtype\fR\&'s\&.
.PP
If \fBstate\fR is set to \fBSDL_IGNORE\fP, that event \fBtype\fR will be automatically dropped from the event queue and will not be filtered\&.
.PP
If \fBstate\fR is set to \fBSDL_ENABLE\fP, that event \fBtype\fR will be processed normally\&.
.PP
If \fBstate\fR is set to \fBSDL_QUERY\fP, \fBSDL_EventState\fP will return the current processing state of the specified event \fBtype\fR\&.
.PP
A list of event \fBtype\fR\&'s can be found in the \fI\fBSDL_Event\fR\fR section\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_Event\fR\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 22:59
