.TH "SDL_CDName" "3" "Tue 11 Sep 2001, 22:58" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_CDName \- Returns a human-readable, system-dependent identifier for the CD-ROM\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBconst char *\fBSDL_CDName\fP\fR(\fBint drive\fR);
.SH "DESCRIPTION"
.PP
Returns a human-readable, system-dependent identifier for the CD-ROM\&. \fBdrive\fR is the index of the drive\&. Drive indices start to 0 and end at \fBSDL_CDNumDrives()\fP-1\&.
.SH "EXAMPLES"
.PP
.IP "   \(bu" 6
"/dev/cdrom"
.IP "   \(bu" 6
"E:"
.IP "   \(bu" 6
"/dev/disk/ide/1/master"
.SH "SEE ALSO"
.PP
\fI\fBSDL_CDNumDrives\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 22:58
