.TH "SDL_CDPlay" "3" "Tue 11 Sep 2001, 22:58" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_CDPlay \- Play a CD
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBint \fBSDL_CDPlay\fP\fR(\fBSDL_CD *cdrom, int start, int length\fR);
.SH "DESCRIPTION"
.PP
Plays the given \fBcdrom\fR, starting a frame \fBstart\fR for \fBlength\fR frames\&.
.SH "RETURN VALUES"
.PP
Returns \fB0\fR on success, or \fB-1\fR on an error\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_CDPlayTracks\fP\fR, \fI\fBSDL_CDStop\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 22:58
