.TH "SDL_WM_IconifyWindow" "3" "Tue 11 Sep 2001, 23:02" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_WM_IconifyWindow \- Iconify/Minimise the window
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBint \fBSDL_WM_IconifyWindow\fP\fR(\fBvoid\fR);
.SH "DESCRIPTION"
.PP
If the application is running in a window managed environment SDL attempts to iconify/minimise it\&. If \fBSDL_WM_IconifyWindow\fP is successful, the application will receive a \fI\fBSDL_APPACTIVE\fP\fR loss event\&.
.SH "RETURN VALUE"
.PP
Returns non-zero on success or \fB0\fR if iconification is not support or was refused by the window manager\&.
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:02
