.TH "SDL_JoystickNumButtons" "3" "Tue 11 Sep 2001, 23:00" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_JoystickNumButtons \- Get the number of joysitck buttons
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBint \fBSDL_JoystickNumButtons\fP\fR(\fBSDL_Joystick *joystick\fR);
.SH "DESCRIPTION"
.PP
Return the number of buttons available from a previously opened \fBSDL_Joystick\fR\&.
.SH "RETURN VALUE"
.PP
Number of buttons\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_JoystickGetButton\fP\fR, \fI\fBSDL_JoystickOpen\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:00
