.TH "SDL_GetKeyName" "3" "Tue 11 Sep 2001, 22:59" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_GetKeyName \- Get the name of an SDL virtual keysym
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBchar *\fBSDL_GetKeyName\fP\fR(\fBSDLKey key\fR);
.SH "DESCRIPTION"
.PP
Returns the SDL-defined name of the \fI\fBSDLKey\fR\fR \fBkey\fR\&.
.SH "SEE ALSO"
.PP
\fI\fBSDLKey\fR\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 22:59
