.TH "SDL_JoystickNumHats" "3" "Tue 11 Sep 2001, 23:00" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_JoystickNumHats \- Get the number of joystick hats
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBint \fBSDL_JoystickNumHats\fP\fR(\fBSDL_Joystick *joystick\fR);
.SH "DESCRIPTION"
.PP
Return the number of hats available from a previously opened \fBSDL_Joystick\fR\&.
.SH "RETURN VALUE"
.PP
Number of hats\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_JoystickGetHat\fP\fR, \fI\fBSDL_JoystickOpen\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:00
