.TH "SDL_MapRGBA" "3" "Tue 11 Sep 2001, 23:01" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_MapRGBA \- Map a RGBA color value to a pixel format\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBUint32 \fBSDL_MapRGBA\fP\fR(\fBSDL_PixelFormat *fmt, Uint8 r, Uint8 g, Uint8 b, Uint8 a\fR);
.SH "DESCRIPTION"
.PP
Maps the RGBA color value to the specified pixel format and returns the pixel value as a 32-bit int\&.
.PP
If the format has a palette (8-bit) the index of the closest matching color in the palette will be returned\&.
.PP
If the specified pixel format has no alpha component the alpha value will be ignored (as it will be in formats with a palette)\&.
.SH "RETURN VALUE"
.PP
A pixel value best approximating the given RGBA color value for a given pixel format\&. If the pixel format bpp (color depth) is less than 32-bpp then the unused upper bits of the return value can safely be ignored (e\&.g\&., with a 16-bpp format the return value can be assigned to a \fBUint16\fP, and similarly a \fBUint8\fP for an 8-bpp format)\&.
.SH "SEE ALSO"
.PP
\fISDL_GetRGB\fR, \fISDL_GetRGBA\fR, \fISDL_MapRGB\fR, \fISDL_PixelFormat\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:01
