.TH "SDL_GL_LoadLibrary" "3" "Tue 11 Sep 2001, 23:01" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_GL_LoadLibrary \- Specify an OpenGL library
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBint \fBSDL_GL_LoadLibrary\fP\fR(\fBconst char *path\fR);
.SH "DESCRIPTION"
.PP
If you wish, you may load the OpenGL library at runtime, this must be done before \fI\fBSDL_SetVideoMode\fP\fR is called\&. The \fBpath\fR of the GL library is passed to \fBSDL_GL_LoadLibrary\fP and it returns \fB0\fR on success, or \fB-1\fR on an error\&. You must then use \fI\fBSDL_GL_GetProcAddress\fP\fR to retrieve function pointers to GL functions\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_GL_GetProcAddress\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:01
