.TH "SDL_CreateMutex" "3" "Tue 11 Sep 2001, 23:00" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_CreateMutex \- Create a mutex
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
#include "SDL_thread\&.h"
.sp
\fBSDL_mutex *\fBSDL_CreateMutex\fP\fR(\fBvoid\fR);
.SH "DESCRIPTION"
.PP
Create a new, unlocked mutex\&.
.SH "EXAMPLES"
.PP
.nf
\f(CWSDL_mutex *mut;

mut=SDL_CreateMutex();
\&.
\&.
if(SDL_mutexP(mut)==-1){
  fprintf(stderr, "Couldn\&'t lock mutex
");
  exit(-1);
}
\&.
/* Do stuff while mutex is locked */
\&.
\&.
if(SDL_mutexV(mut)==-1){
  fprintf(stderr, "Couldn\&'t unlock mutex
");
  exit(-1);
}

SDL_DestroyMutex(mut);
\fR
.fi
.PP
.SH "SEE ALSO"
.PP
\fI\fBSDL_mutexP\fP\fR, \fI\fBSDL_mutexV\fP\fR, \fI\fBSDL_DestroyMutex\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:00
