.TH "SDL_SysWMEvent" "3" "Tue 11 Sep 2001, 23:00" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_SysWMEvent \- Platform-dependent window manager event\&.
.SH "DESCRIPTION"
.PP
The system window manager event contains a pointer to system-specific information about unknown window manager events\&. If you enable this event using \fI\fBSDL_EventState()\fP\fR, it will be generated whenever unhandled events are received from the window manager\&. This can be used, for example, to implement cut-and-paste in your application\&. 
.PP
.nf
\f(CWtypedef struct {
         Uint8 type;   /* Always SDL_SysWM */
 } SDL_SysWMEvent;\fR
.fi
.PP
 If you want to obtain system-specific information about the window manager, you can fill the version member of a \fBSDL_SysWMinfo\fR structure (details can be found in \fBSDL_syswm\&.h\fP, which must be included) using the \fBSDL_VERSION()\fP macro found in \fBSDL_version\&.h\fP, and pass it to the function: 
.PP
.sp
\fBint \fBSDL_GetWMInfo\fP\fR(\fBSDL_SysWMinfo *info\fR);
.SH "SEE ALSO"
.PP
\fI\fBSDL_EventState\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:00
