.TH "SDL_JoystickNumAxes" "3" "Tue 11 Sep 2001, 23:00" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_JoystickNumAxes \- Get the number of joystick axes
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBint \fBSDL_JoystickNumAxes\fP\fR(\fBSDL_Joystick *joystick\fR);
.SH "DESCRIPTION"
.PP
Return the number of axes available from a previously opened \fBSDL_Joystick\fR\&.
.SH "RETURN VALUE"
.PP
Number of axes\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_JoystickGetAxis\fP\fR, \fI\fBSDL_JoystickOpen\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:00
