.TH "SDL_SaveBMP" "3" "Tue 11 Sep 2001, 23:01" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_SaveBMP \- Save an SDL_Surface as a Windows BMP file\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBint \fBSDL_SaveBMP\fP\fR(\fBSDL_Surface *surface, const char *file\fR);
.SH "DESCRIPTION"
.PP
Saves the \fBSDL_Surface\fR \fBsurface\fR as a Windows BMP file named \fBfile\fR\&.
.SH "RETURN VALUE"
.PP
Returns \fB0\fR if successful or \fB-1\fR if there was an error\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_LoadBMP\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:01
