.TH "SDL_CreateRGBSurfaceFrom" "3" "Tue 11 Sep 2001, 23:01" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_CreateRGBSurfaceFrom \- Create an SDL_Surface from pixel data
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBSDL_Surface *\fBSDL_CreateRGBSurfaceFrom\fP\fR(\fBvoid *pixels, int width, int height, int depth, int pitch, Uint32 Rmask, Uint32 Gmask, Uint32 Bmask, Uint32 Amask\fR);
.SH "DESCRIPTION"
.PP
Creates an SDL_Surface from the provided pixel data\&.
.PP
The data stored in \fBpixels\fR is assumed to be of the \fBdepth\fR specified in the parameter list\&. The pixel data is not copied into the \fBSDL_Surface\fR structure so it should not be freed until the surface has been freed with a called to \fISDL_FreeSurface\fR\&. \fBpitch\fR is the length of each scanline in bytes\&. 
.PP
See \fI\fBSDL_CreateRGBSurface\fP\fR for a more detailed description of the other parameters\&.
.SH "RETURN VALUE"
.PP
Returns the created surface, or \fBNULL\fR upon error\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_CreateRGBSurface\fP\fR, \fI\fBSDL_FreeSurface\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:01
