.TH "SDL_CondBroadcast" "3" "Tue 11 Sep 2001, 23:00" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_CondBroadcast \- Restart all threads waiting on a condition variable
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
#include "SDL_thread\&.h"
.sp
\fBint \fBSDL_CondBroadcast\fP\fR(\fBSDL_cond *cond\fR);
.SH "DESCRIPTION"
.PP
Restarts all threads that are waiting on the condition variable, \fBcond\fR\&. Returns \fB0\fR on success, or \fB-1\fR on an error\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_CondSignal\fP\fR, \fI\fBSDL_CondWait\fP\fR 
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:00
