.TH "SDL_Init" "3" "Tue 11 Sep 2001, 23:00" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_Init \- Initializes SDL
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBint \fBSDL_Init\fP\fR(\fBUint32 flags\fR);
.SH "DESCRIPTION"
.PP
Initializes SDL\&. This should be called before all other SDL functions\&. The \fBflags\fR parameter specifies what part(s) of SDL to initialize\&.
.TP 20
\fBSDL_INIT_TIMER\fP
Initializes the \fItimer\fR subsystem\&.
.TP 20
\fBSDL_INIT_AUDIO\fP
Initializes the \fIaudio\fR subsystem\&.
.TP 20
\fBSDL_INIT_VIDEO\fP
Initializes the \fIvideo\fR subsystem\&.
.TP 20
\fBSDL_INIT_CDROM\fP
Initializes the \fIcdrom\fR subsystem\&.
.TP 20
\fBSDL_INIT_JOYSTICK\fP
Initializes the \fIjoystick\fR subsystem\&.
.TP 20
\fBSDL_INIT_EVERYTHING\fP
Initialize all of the above\&.
.TP 20
\fBSDL_INIT_NOPARACHUTE\fP
Prevents SDL from catching fatal signals\&.
.TP 20
\fBSDL_INIT_EVENTTHREAD\fP
.SH "RETURN VALUE"
.PP
Returns \fB-1\fR on an error or \fB0\fR on success\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_Quit\fP\fR, \fI\fBSDL_InitSubSystem\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:00
