.TH "SDL_JoystickName" "3" "Tue 11 Sep 2001, 23:00" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_JoystickName \- Get joystick name\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBconst char *\fBSDL_JoystickName\fP\fR(\fBint index\fR);
.SH "DESCRIPTION"
.PP
Get the implementation dependent name of joystick\&. The \fBindex\fR parameter refers to the N\&'th joystick on the system\&.
.SH "RETURN VALUE"
.PP
Returns a char pointer to the joystick name\&.
.SH "EXAMPLES"
.PP
.PP
.nf
\f(CW/* Print the names of all attached joysticks */
int num_joy, i;
num_joy=SDL_NumJoysticks();
printf("%d joysticks found
", num_joy);
for(i=0;i<num_joy;i++)
  printf("%s
", SDL_JoystickName(i));\fR
.fi
.PP
.SH "SEE ALSO"
.PP
\fI\fBSDL_JoystickOpen\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:00
