.TH "SDL_GetVideoSurface" "3" "Tue 11 Sep 2001, 23:01" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_GetVideoSurface \- returns a pointer to the current display surface
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBSDL_Surface *\fBSDL_GetVideoSurface\fP\fR(\fBvoid\fR);
.SH "DESCRIPTION"
.PP
This function returns a pointer to the current display surface\&. If SDL is doing format conversion on the display surface, this function returns the publicly visible surface, not the real video surface\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_Surface\fR\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:01
