.TH "SDL_WaitThread" "3" "Tue 11 Sep 2001, 23:01" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_WaitThread \- Wait for a thread to finish\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
#include "SDL_thread\&.h"
.sp
\fBvoid \fBSDL_WaitThread\fP\fR(\fBSDL_Thread *thread, int *status\fR);
.SH "DESCRIPTION"
.PP
Wait for a thread to finish (timeouts are not supported)\&.
.SH "RETURN VALUE"
.PP
The return code for the thread function is placed in the area pointed to by \fBstatus\fR, if \fBstatus\fR is not \fBNULL\fR\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_CreateThread\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:01
