.TH "SDL_GetGammaRamp" "3" "Tue 11 Sep 2001, 23:01" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_GetGammaRamp \- Gets the color gamma lookup tables for the display
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBint \fBSDL_GetGammaRamp\fP\fR(\fBUint16 *redtable, Uint16 *greentable, Uint16 *bluetable\fR);
.SH "DESCRIPTION"
.PP
Gets the gamma translation lookup tables currently used by the display\&. Each table is an array of 256 Uint16 values\&.
.PP
Not all display hardware is able to change gamma\&.
.SH "RETURN VALUE"
.PP
Returns -1 on error\&.
.SH "SEE ALSO"
.PP
\fISDL_SetGamma\fR \fISDL_SetGammaRamp\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:01
