.TH "SDL_JoystickUpdate" "3" "Tue 11 Sep 2001, 23:00" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_JoystickUpdate \- Updates the state of all joysticks
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBvoid \fBSDL_JoystickUpdate\fP\fR(\fBvoid\fR);
.SH "DESCRIPTION"
.PP
Updates the state(position, buttons, etc\&.) of all open joysticks\&. If joystick events have been enabled with \fI\fBSDL_JoystickEventState\fP\fR then this is called automatically in the event loop\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_JoystickEventState\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:00
