.TH "SDL_PumpEvents" "3" "Tue 11 Sep 2001, 22:59" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_PumpEvents \- Pumps the event loop, gathering events from the input devices\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBvoid \fBSDL_PumpEvents\fP\fR(\fBvoid\fR);
.SH "DESCRIPTION"
.PP
Pumps the event loop, gathering events from the input devices\&.
.PP
\fBSDL_PumpEvents\fP gathers all the pending input information from devices and places it on the event queue\&. Without calls to \fBSDL_PumpEvents\fP no events would ever be placed on the queue\&. Often calls the need for \fBSDL_PumpEvents\fP is hidden from the user since \fI\fBSDL_PollEvent\fP\fR and \fI\fBSDL_WaitEvent\fP\fR implicitly call \fBSDL_PumpEvents\fP\&. However, if you are not polling or waiting for events (e\&.g\&. your filtering them), then you must call \fBSDL_PumpEvents\fP to force an event queue update\&.
.PP
.RS
\fBNote:  
.PP
You can only call this function in the thread that set the video mode\&.
.RE
.SH "SEE ALSO"
.PP
\fI\fBSDL_PollEvent\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 22:59
