.TH "SDL_SetCursor" "3" "Tue 11 Sep 2001, 23:01" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_SetCursor \- Set the currently active mouse cursor\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBvoid \fBSDL_SetCursor\fP\fR(\fBSDL_Cursor *cursor\fR);
.SH "DESCRIPTION"
.PP
Sets the currently active cursor to the specified one\&. If the cursor is currently visible, the change will be immediately represented on the display\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_GetCursor\fP\fR, \fI\fBSDL_CreateCursor\fP\fR, \fI\fBSDL_ShowCursor\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:01
