.TH "SDL_DestroyMutex" "3" "Tue 11 Sep 2001, 23:00" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_DestroyMutex \- Destroy a mutex
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
#include "SDL_thread\&.h"
.sp
\fBvoid \fBSDL_DestroyMutex\fP\fR(\fBSDL_mutex *mutex\fR);
.SH "DESCRIPTION"
.PP
Destroy a previously \fIcreated\fR mutex\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_CreateMutex\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:00
