.TH "SDL_WM_SetIcon" "3" "Tue 11 Sep 2001, 23:02" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_WM_SetIcon \- Sets the icon for the display window\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBvoid \fBSDL_WM_SetIcon\fP\fR(\fBSDL_Surface *icon, Uint8 *mask\fR);
.SH "DESCRIPTION"
.PP
Sets the icon for the display window\&. Win32 icons must be 32x32\&.
.PP
This function must be called before the first call to \fISDL_SetVideoMode\fR\&.
.PP
It takes an \fBicon\fR surface, and a \fBmask\fR in MSB format\&.
.PP
If \fBmask\fR is \fBNULL\fP, the entire icon surface will be used as the icon\&.
.SH "EXAMPLE"
.PP
.nf
\f(CWSDL_WM_SetIcon(SDL_LoadBMP("icon\&.bmp"), NULL);\fR
.fi
.PP
.SH "SEE ALSO"
.PP
\fI\fBSDL_SetVideoMode\fP\fR, \fI\fBSDL_WM_SetCaption\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:02
