.TH "SDL_GLattr" "3" "Tue 11 Sep 2001, 23:01" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_GLattr \- SDL GL Attributes
.SH "ATTRIBUTES"
.TP 20
\fBSDL_GL_RED_SIZE\fP
Size of the framebuffer red component, in bits
.TP 20
\fBSDL_GL_GREEN_SIZE\fP
Size of the framebuffer green component, in bits
.TP 20
\fBSDL_GL_BLUE_SIZE\fP
Size of the framebuffer blue component, in bits
.TP 20
\fBSDL_GL_ALPHA_SIZE\fP
Size of the framebuffer alpha component, in bits
.TP 20
\fBSDL_GL_DOUBLEBUFFER\fP
0 or 1, enable or disable double buffering
.TP 20
\fBSDL_GL_BUFFER_SIZE\fP
Size of the framebuffer, in bits
.TP 20
\fBSDL_GL_DEPTH_SIZE\fP
Size of the depth buffer, in bits
.TP 20
\fBSDL_GL_STENCIL_SIZE\fP
Size of the stencil buffer, in bits
.TP 20
\fBSDL_GL_ACCUM_RED_SIZE\fP
Size of the accumulation buffer red component, in bits
.TP 20
\fBSDL_GL_ACCUM_GREEN_SIZE\fP
Size of the accumulation buffer green component, in bits
.TP 20
\fBSDL_GL_ACCUM_BLUE_SIZE\fP
Size of the accumulation buffer blue component, in bits
.TP 20
\fBSDL_GL_ACCUM_ALPHA_SIZE\fP
Size of the accumulation buffer alpha component, in bits
.SH "DESCRIPTION"
.PP
While you can set most OpenGL attributes normally, the attributes list above must be known \fIbefore\fP SDL sets the video mode\&. These attributes a set and read with \fI\fBSDL_GL_SetAttribute\fP\fR and \fI\fBSDL_GL_GetAttribute\fP\fR\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_GL_SetAttribute\fP\fR, \fI\fBSDL_GL_GetAttribute\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:01
