.TH "SDL_RemoveTimer" "3" "Tue 11 Sep 2001, 23:01" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_RemoveTimer \- Remove a timer which was added with \fISDL_AddTimer\fR\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBSDL_bool \fBSDL_RemoveTimer\fP\fR(\fBSDL_TimerID id\fR);
.SH "DESCRIPTION"
.PP
Removes a timer callback previously added with \fISDL_AddTimer\fR\&.
.SH "RETURN VALUE"
.PP
Returns a boolean value indicating success\&.
.SH "EXAMPLES"
.PP
.PP
.nf
\f(CWSDL_RemoveTimer(my_timer_id);\fR
.fi
.PP
.SH "SEE ALSO"
.PP
\fI\fBSDL_AddTimer\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:01
