.TH "SDL_GetClipRect" "3" "Tue 11 Sep 2001, 23:01" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_GetClipRect \- Gets the clipping rectangle for a surface\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBvoid \fBSDL_GetClipRect\fP\fR(\fBSDL_Surface *surface, SDL_Rect *rect\fR);
.SH "DESCRIPTION"
.PP
Gets the clipping rectangle for a surface\&. When this surface is the destination of a blit, only the area within the clip rectangle is drawn into\&.
.PP
The rectangle pointed to by \fBrect\fR will be filled with the clipping rectangle of the surface\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_SetClipRect\fP\fR, \fI\fBSDL_BlitSurface\fP\fR, \fI\fBSDL_Surface\fR\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:01
