.TH "SDL_UnlockAudio" "3" "Tue 11 Sep 2001, 22:58" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_UnlockAudio \- Unlock the callback function
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBvoid \fBSDL_UnlockAudio\fP\fR(\fBvoid\fR)
.SH "DESCRIPTION"
.PP
Unlocks a previous \fI\fBSDL_LockAudio\fP\fR call\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_OpenAudio\fP\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 22:58
