.TH "SDL_GL_GetAttribute" "3" "Tue 11 Sep 2001, 23:01" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_GL_GetAttribute \- Get the value of a special SDL/OpenGL attribute
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBint \fBSDL_GL_GetAttribute\fP\fR(\fBSDLGLattr attr, int *value\fR);
.SH "DESCRIPTION"
.PP
Places the value of the SDL/OpenGL \fIattribute\fR \fBattr\fR into \fBvalue\fR\&. This is useful after a call to \fI\fBSDL_SetVideoMode\fP\fR to check whether your attributes have been \fIset\fR as you expected\&.
.SH "RETURN VALUE"
.PP
Returns \fB0\fR on success, or \fB-1\fR on an error\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_GL_SetAttribute\fP\fR, \fIGL Attributes\fR
.\" created by instant / docbook-to-man, Tue 11 Sep 2001, 23:01
