#TODO make all dependencies work
[source]
git = "https://github.com/matt-kimball/allocscope"
shallow_clone = true
[build]
template = "cargo"
cargopackages = [
    "allocscope-trace",
    "allocscope-view",
]
dependencies = [
    "libiberty",
    "ncursesw",
    "sqlite3",
    "libunwind",
]
