[source]
same_as = "../../../libs/mesa"

[build]
template = "custom"
dependencies = [
    "expat",
    "libdrm",
    "libx11",
    "libxcb",
    "libxext",
    "libxfixes",
    "libxrandr",
    "libxshmfence",
    "libxxf86vm",
    "llvm21",
    "zlib",
]
dev-dependencies = [
    "llvm21.dev",
]

script = """
DYNAMIC_INIT

if [ "${COOKBOOK_DYNAMIC}" = "1" ]; then
    COOKBOOK_MESON_FLAGS+=(-Dglx=dri)
else
    COOKBOOK_MESON_FLAGS+=(-Dglx=xlib -Dshared-glapi=disabled)
fi

cookbook_meson \
    -Ddri-drivers-path=/usr/lib/dri \
    -Degl=disabled \
    -Dllvm=enabled \
    -Dgles1=disabled \
    -Dgles2=disabled \
    -Dplatforms=x11 \
    -Dshader-cache=disabled
"""
