#TODO missing script for gnu make: https://guide.munin-monitoring.org/en/latest/installation/install.html#installing-munin-from-source
[source]
git = "https://github.com/munin-monitoring/munin"
rev = "2.0.76"
shallow_clone = true
[build]
template = "custom"
