#TODO protobuf in redox
[source]
git = "https://github.com/mobile-shell/mosh"
rev = "mosh-1.4.0"
shallow_clone = true
script = """
./autogen.sh
"""

[build]
template = "configure"
dependencies = [
    "openssl3",
    "ncursesw",
    "zlib",
    "protobuf"
]
dev-dependencies = [
    "host:protobuf"
]
