#TODO No rule to make target 'config.h', needed by 'thttpd.o'
# build instructions: read the INSTALL file
[source]
tar = "https://acme.com/software/thttpd/thttpd-2.29.tar.gz"
[build]
template = "configure"
