#TODO not compiled or tested
# build instructions: https://qmcpack.readthedocs.io/en/develop/installation.html#building-with-cmake
# probably missing dependencies
[source]
git = "https://github.com/QMCPACK/qmcpack"
rev = "v4.2.0"
shallow_clone = true
[build]
template = "cmake"
cmakeflags = [
    "-DBUILD_UNIT_TESTS=OFF"
]
dependencies = [
    "openmpi",
    "openblas",
    "hdf5",
    "libxml2",
    "boost",
    "fftw",
]
