#TODO dependency conflict. Glew wants GLX but mesa uses orbital backend.
# build instructions: https://github.com/yvt/openspades#on-unixes-from-source
[source]
git = "https://github.com/siecvi/zerospades"
rev = "110e573b5bee4570d97507dd9a6989f855520f72"
shallow_clone = true
patches = [
    "redox.patch"
]

[build]
template = "custom"
dependencies = [
    "glew",
    "openssl3",
    "sdl2",
    "sdl2-image",
    "freealut",
    "freetype2",
    "libopus",
    "opusfile",
    "libjpeg",
    "openal",
    "curl",
    "libxinerama",
    "libxft",
]
dev-dependencies = [
    "libstdcxx",
]
script = """
DYNAMIC_INIT
COOKBOOK_CMAKE_FLAGS+=(
    -DOPENSPADES_NONFREE_RESOURCES=OFF
    -DUSE_INTERNAL_OPENAL=OFF
)
cookbook_cmake
"""

[package]
dependencies = [
    "openspades-free-pak"
]
