#TODO build error
# build instructions: https://github.com/yvt/openspades#on-unixes-from-source
[source]
git = "https://github.com/siecvi/zerospades"
rev = "6e01801c5c1fb96457a43698c2f9f7f4f3c8a8a4"
shallow_clone = true
patches = [
    "redox.patch"
]

[build]
template = "custom"
dependencies = [
    "glew",
    "openssl3",
    "sdl2",
    "sdl2-image",
    "freealut",
    "freetype2",
    "libopus",
    "opusfile",
    "libjpeg",
    "openal",
    "curl",
    "libxinerama",
    "libxft",
]
dev-dependencies = [
    "libstdcxx",
]
script = """
DYNAMIC_INIT
COOKBOOK_CMAKE_FLAGS+=(
    -DOPENSPADES_NONFREE_RESOURCES=OFF
    -DUSE_INTERNAL_OPENAL=OFF
)
cookbook_cmake
"""

[package]
dependencies = [
    "openspades-free-pak"
]
