#TODO webbrowser crate error
[source]
git = "https://github.com/BVE-Reborn/rend3"
shallow_clone = true
[build]
template = "cargo"
cargopackageprefixed = true
cargopackages = ["rend3-examples-package"]
