#TODO not compiled or tested
[source]
git = "https://github.com/vanhauser-thc/thc-hydra"
rev = "v9.7"
shallow_clone = true
[build]
template = "configure"
#dependencies = [
#    "openssl3",
#    "libssh",
#    "memcached",
#]
