[source]
git = "https://gitlab.redox-os.org/Ibuki.O/kernel.git"
branch = "remove-fd-allocation"

[build]
template = "custom"
script = """
cd "${COOKBOOK_SOURCE}"
make install BUILD="${COOKBOOK_BUILD}" DESTDIR="${COOKBOOK_STAGE}"
"""
