[source]
git = "https://gitlab.redox-os.org/redox-os/winit"
branch = "redox-0.31.0-beta"

[build]
template = "cargo"
cargopath = "winit"
cargoexamples = [
    "application",
    "child_window",
    "control_flow",
    "dnd",
    "ime",
    "pump_events",
    "run_on_demand",
    "window",
]
clearlocked = true
