[package]
dependencies = [
    "caja",
    "dconf",
    "marco",
    "mate-control-center",
    "mate-icon-theme",
    "mate-panel",
    "mate-session-manager",
    "mate-settings-daemon",
    "mate-terminal",
    "mate-themes",
]
