#TODO build and test disabled examples
[source]
git = "https://github.com/DioxusLabs/taffy"
shallow_clone = true
[build]
template = "cargo"
cargoexamples = [
    "basic",
    #"image",
    #"text",
    #"cosmic-text-example",
]
