#TODO compile and test
[source]
git = "https://gitlab.redox-os.org/redox-os/rust-cairo-demo"
shallow_clone = true
[build]
template = "cargo"
dependencies = [
    "cairo",
    "expat",
    "fontconfig",
    "freetype2",
    "libpng",
    "pixman",
    "zlib",
]
