#TODO implement go template
# build instructions: https://github.com/kahing/goofys/#installation
[source]
git = "https://github.com/kahing/goofys"
rev = "v0.24.0"
shallow_clone = true
[build]
template = "go"
