#TODO compile and test
# build instructions: https://invent.kde.org/multimedia/kdenlive/-/blob/master/dev-docs/build.md#build-and-install-the-projects
[source]
git = "https://invent.kde.org/multimedia/kdenlive"
rev = "v26.04.2"
shallow_clone = true
[build]
template = "cmake"
cmakeflags = [
    "-DBUILD_TESTING=OFF",
    "-DUSE_DBUS=OFF",
]
dependencies = [
     "mlt",
     "opentimelineio",
     "libimath",
     "qt6-base",
     "ffmpeg6",
     "qt6-declarative",
     "qt6-multimedia",
     "qt6-svg",
     "qt6-networkauth",
     "ki18n6",
     "karchive6",
     "kbookmarks6",
     "kcodecs6",
     "kcoreaddons6",
     "kconfig6",
     "kconfigwidgets6",
     "kio6",
     "kwidgetsaddons6",
     "knotifyconfig6",
     "knewstuff6",
     "kxmlgui6",
     "knotifications6",
     "kguiaddons6",
     "ktextwidgets6",
     "kiconthemes6",
     "solid6",
     "kfilemetadata6",
     "purpose6",
#     "breeze-icons",
]
