[source]
git = "https://github.com/pypa/setuptools"
rev = "v83.0.0"
shallow_clone = true

[build]
template = "python"
legacysetup = true
dev-dependencies = [
    "host:python312",
    "python312",
]

[package]
dependencies = [
    "python312"
]

