#TODO camino crate error
# build instructions: https://github.com/ruffle-rs/ruffle#building-from-source
[source]
git = "https://github.com/ruffle-rs/ruffle"
shallow_clone = true
[build]
template = "cargo"
cargopackages = ["ruffle_desktop"]
dependencies = [
	"openssl3",
]
