#TODO cubecl-macros crate error
[source]
git = "https://github.com/tracel-ai/cubecl"
shallow_clone = true
[build]
template = "cargo"
cargopackages = [
    "gelu"
]
cargoflags = ["--no-default-features --wgpu"]
