[source]
git = "https://github.com/cython/cython"
rev = "3.2.4"
shallow_clone = true

[build]
template = "python"
dev-dependencies = [
    "host:python312",
    "host:python3-setuptools",
]

[package]
dependencies = [
    "python312"
]
