[source]
same_as = "../../core/installer"

[build]
template = "custom"
script = """
DYNAMIC_INIT
COOKBOOK_CARGO_PATH="gui" cookbook_cargo

mkdir -pv "${COOKBOOK_STAGE}/usr/share/ui/apps"
cp -v "${COOKBOOK_RECIPE}/manifest" "${COOKBOOK_STAGE}/usr/share/ui/apps/redox-installer-gui"
"""
