[source]
tar = "https://www.x.org/releases/individual/lib/libxshmfence-1.3.tar.gz"
blake3 = "17784f567543f3cdf4ee7b0a45f30dbb91acd1fd4f5f398e274376f301da6df8"
script = """
autotools_recursive_regenerate
"""

[build]
dependencies = [
    "x11proto",
]
template = "custom"
script = """
DYNAMIC_INIT
cookbook_configure
"""
