#TODO add script for proper packaging
# use the "./run" command to run
# build instructions: https://github.com/ankitects/anki/blob/main/docs/development.md#building-from-source
[source]
git = "https://github.com/ankitects/anki"
rev = "25.09.4"
shallow_clone = true
[build]
template = "custom"
script = """
mkdir -pv "${COOKBOOK_STAGE}/home/user/anki"
cp -rv "${COOKBOOK_SOURCE}"/* "${COOKBOOK_STAGE}/home/user/anki"
"""
[package]
dependencies = [
    "python312"
]
