[source]
git = "https://github.com/jackpot51/iced.git"
branch = "redox-wayland"

[build]
dependencies = [
    "libwayland",
    "libxkbcommon",
]
template = "custom"
script = """
DYNAMIC_INIT
COOKBOOK_CARGO_PATH="examples/sctk_lazy" cookbook_cargo_build
"""
