# TODO make this the no tiles variant, may want separate dcss-tiles recipe for tiles
# TODO compilation instructions: https://github.com/crawl/crawl/blob/master/crawl-ref/INSTALL.md#compiling
# TODO not sure how to get PyYAML installed, may need to be separately packaged
[source]
tar = "https://github.com/crawl/crawl/releases/download/0.34.1/stone_soup-0.34.1-nodeps.tar.xz"
[build]
template = "custom"
dependencies = [
    "lua54",
    "ncursesw",
    "pcre",
    "sqlite3",
    "zlib",
]
dev-dependencies = [
    "host:perl5",
    "host:python312",
]
script = """
DYNAMIC_INIT
# Copy source to build directory
rsync -av --delete "${COOKBOOK_SOURCE}/" ./


cd "${COOKBOOK_SOURCE}/"source
"${COOKBOOK_MAKE}" -j"$($NPROC)"

mkdir -pv "${COOKBOOK_STAGE}/usr/games"
cp -v "${COOKBOOK_BUILD}/crawl" "${COOKBOOK_STAGE}/usr/games"
"""
