#TODO not compiled or tested
# build instructions: https://github.com/dbalsom/martypc/wiki/Building-MartyPC#building-for-linux
[source]
git = "https://github.com/dbalsom/martypc"
shallow_clone = true
[build]
template = "cargo"
cargopackages = ["martypc_eframe"]
