#TODO add script for scons: https://github.com/gordan-bobic/zfs-fuse/blob/master/INSTALL#L37
[source]
git = "https://github.com/gordan-bobic/zfs-fuse"
rev = "d286672f25602583aaf91ef0fa511d03ab4d3aab"
shallow_clone = true
[build]
template = "custom"
dependencies = [
    "libfuse2",
    #"libaio",
    "zlib",
]
