#TODO compile and test
# build instructions: https://git.dynare.org/Dynare/dynare#general-instructions
[source]
tar = "https://www.dynare.org/release/source/dynare-7.0.tar.xz"
[build]
template = "meson"
mesonflags = [
    "-Dbuild_for=octave"
]
dependencies = [
    "octave",
    "boost",
    "slicot",
]
