#TODO finish cross-compilation script
# build instructions: https://github.com/helio-fm/helio-sequencer/blob/develop/Docs/readme.md#building-from-source
[source]
git = "https://github.com/helio-fm/helio-sequencer"
rev = "3.17"
shallow_clone = true
[build]
template = "custom"
script = """
DYNAMIC_INIT
rsync -av --delete "${COOKBOOK_SOURCE}/" ./
cd Projects/LinuxMakefile
make CONFIG=Release64
"""
