# Default build system configuration

include = ["desktop-minimal.toml", "server.toml"]

# General settings
[general]
# Filesystem size in MiB
filesystem_size = 650

# Package settings
[packages]
cosmic-edit = {}
cosmic-files = {}
cosmic-icons = {}
cosmic-term = {}
dejavu = {}
freefont = {}
hicolor-icon-theme = {}
installer-gui = {}
netsurf = {}
patchelf = {}
pop-icon-theme = {}
shared-mime-info = {}
# orbterm from desktop-minimal should be ignored
orbterm = "ignore"
