# Configuration for development

include = ["desktop.toml"]

# General settings
[general]
# Filesystem size in MiB
filesystem_size = 3000
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]
gcc13 = {}
hello-redox = {}
