# Configuration for testing

include = ["server.toml"]

# General settings
[general]
# Filesystem size in MiB
filesystem_size = 10000
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]
acid = {}
resist = {}
relibc-tests = {}
os-test = {}
openposixtestsuite = {}
redox-posix-tests = {}
vttest = {}
benchmarks = {}

[[files]]
path = "/home/user/test.rs"
data = """
fn main() {
    println!("Hello, Redox!");
}
"""

[[files]]
path = "/home/user/test.c"
data = """
#include <stdio.h>

int main(void) {
	printf("Hello, Redox!\\n");
}
"""

[[files]]
path = "/home/user/test.cpp"
data = """
#include <iostream>

int main()
{
   std::cout << "Hello, Redox!" << std::endl;
}
"""

[[files]]
path = "/home/user/test.py"
data = """
print("Hello, Redox!")
"""

[[files]]
path = "/home/user/test.lua"
data = """
print("Hello, Redox!")
"""

[[files]]
path = "/home/user/test.js"
data = """
console.log("Hello Redox");
"""

[[files]]
path = "/home/user/test.java"
data = """
public class Java {
	public static void main(String[] args) {
		System.out.println("Hello Redox");
	}
}
"""
