#TODO determine minimum dependencies from meson log
[source]
tar = "https://sources.phosh.mobi/releases/phosh-mobile-settings/phosh-mobile-settings-0.56.0.tar.xz"
[build]
template = "meson"
mesonflags = [
    "-Dintrospection=false"
]
