#TODO need testing
[source]
tar = "https://webkitgtk.org/releases/webkitgtk-2.49.1.tar.xz"
blake3 = "7f04acb2f909ad334fc623afb297ebca1d5a5005bda1682946fb37e044e45ecb"
patches = ["redox.patch"]

[build]
template = "custom"
dependencies = [
    "gstreamer",
    "gtk3",
    "libatomic",
    "libavif",
    "libgcrypt",
    "libhyphen",
    "libsoup",
    "libtasn1",
    "libwebp",
    "libwoff2",
    "libxslt",
    "libjxl",
    "sqlite3",
]
dev-dependencies = [
    "host:gperf",
    "libstdcxx",
]
script = """
DYNAMIC_INIT
export WEBKIT_USE_SCCACHE=1
export PYTHONDONTWRITEBYTECODE=1
COOKBOOK_CMAKE_FLAGS+=(
# common flags
    -DPORT=GTK
    -DUNIX=1
    -DUSE_GTK4=OFF
# due to lack of dbus
    -DENABLE_NOTIFICATIONS=OFF
    -DENABLE_GAMEPAD=OFF
    -DENABLE_MEDIA_STREAM=OFF
    -DENABLE_BUBBLEWRAP_SANDBOX=OFF
    -DENABLE_INTROSPECTION=OFF
    -DENABLE_JOURNALD_LOG=OFF
# jit issues
    -DENABLE_JIT=OFF
    -DENABLE_DFG_JIT=OFF
    -DENABLE_FTL_JIT=OFF
# hardware/library issues
    -DENABLE_SPEECH_SYNTHESIS=OFF
    -DENABLE_SPELLCHECK=OFF # libenchant
    -DUSE_LIBBACKTRACE=OFF
    -DUSE_LIBDRM=OFF
    -DUSE_LIBSECRET=OFF
    -DUSE_SYSPROF_CAPTURE=OFF
    -DUSE_SYSTEM_SYSPROF_CAPTURE=OFF
    -DENABLE_GEOLOCATION=OFF
    -DUSE_LCMS=OFF
)

cookbook_cmake

patchelf --replace-needed "${COOKBOOK_SYSROOT}/usr/lib/libsqlite3.so" "libsqlite3.so" "${COOKBOOK_STAGE}/usr/lib/libwebkit2gtk-4.1.so"
patchelf --replace-needed "${COOKBOOK_SYSROOT}/usr/lib/libsqlite3.so" "libsqlite3.so" "${COOKBOOK_STAGE}/usr/libexec/webkit2gtk-4.1/MiniBrowser"
mkdir -p "${COOKBOOK_STAGE}/usr/bin"
ln -sr "${COOKBOOK_STAGE}/usr/libexec/webkit2gtk-4.1/MiniBrowser" "${COOKBOOK_STAGE}/usr/bin/MiniBrowser"
"""

[package]
dependencies = ["glib-networking"]
