#TODO camino crate error (after a patch on the ring crate)
[source]
git = "https://github.com/rustsec/rustsec"
shallow_clone = true
[build]
template = "custom"
dependencies = [
    "openssl3",
    "libssh2",
]
script = """
DYNAMIC_INIT
export OPENSSL_DIR="${COOKBOOK_SYSROOT}"
cookbook_cargo_packages cargo-audit
"""
