#TODO not compiled or tested
#TODO determine minimum dependencies from cmake log
[source]
git = "https://invent.kde.org/plasma/discover"
rev = "v6.6.5"
shallow_clone = true
[build]
template = "cmake"
dev-dependencies = ["host:ecm"]
