#TODO compiled but not tested
[source]
git = "https://github.com/ad4mx/spinoff"
shallow_clone = true
[build]
template = "cargo"
cargoexamples = [
    "simple",
    "stop_and_persist",
    "stream",
]
