#TODO not compiled or tested
# build instructions: https://github.com/google/shaderc#getting-and-building-shaderc
[source]
git = "https://github.com/google/shaderc"
rev = "v2026.2"
[build]
template = "cmake"
cmakeflags = [
    "-DSHADERC_ENABLE_HLSL=OFF",
    "-DSHADERC_SKIP_TESTS=ON",
    "-DSHADERC_SKIP_EXAMPLES=ON",
]
dev-dependencies = [
    "host:spirv-tools",
]
