[source]
git = "https://github.com/LekKit/RVVM.git"

[build]
template = "custom"

# TODO: Use SDL2?
dependencies = [
    "sdl1",
    "liborbital",
]

script = """
DYNAMIC_INIT
export BUILDDIR="${COOKBOOK_BUILD}"
export DESTDIR="${COOKBOOK_STAGE}"
# Use SDL1
export USE_SDL=1
export OS=Redox

# Let's goo
"${COOKBOOK_MAKE}" install -C "${COOKBOOK_SOURCE}"
"""
