[package]
dependencies = [
    "dev-essential",
    "redox-tests",
    "exampled",
    "gdbserver",
    "libgmp",
    "libiconv",
    "liborbital",
    "libsodium",
    "libxml2",
    "ncursesw",
    "nghttp2",
    "openssl3",
    "orbclient",
    "pcre",
    "terminfo",
    "xz",
    "zlib",
]
