#TODO not compiled or tested
[source]
tar = "https://cdn.kernel.org/pub/linux/kernel/v7.x/linux-7.0.3.tar.xz"
blake3 = "d9b0776504d3b1f03bdd4ce638110a4070a4dabed57fcc83e4940e9bbf7cbc0b"

[build]
template = "custom"
dev-dependencies = [
    "host:elfutils",
    "host:bc",
]
script = """
pushd "$COOKBOOK_SOURCE"
make "O=$COOKBOOK_BUILD" tinyconfig
popd

export KBUILD_OUTPUT=$COOKBOOK_BUILD
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_64BIT
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_BLK_DEV_INITRD
${COOKBOOK_SOURCE}/scripts/config --disable CONFIG_RD_GZIP
${COOKBOOK_SOURCE}/scripts/config --disable CONFIG_RD_BZIP2
${COOKBOOK_SOURCE}/scripts/config --disable CONFIG_RD_LZMA
${COOKBOOK_SOURCE}/scripts/config --disable CONFIG_RD_XZ
${COOKBOOK_SOURCE}/scripts/config --disable CONFIG_RD_LZO
${COOKBOOK_SOURCE}/scripts/config --disable CONFIG_RD_LZ4
${COOKBOOK_SOURCE}/scripts/config --disable CONFIG_RD_ZSTD
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_EXPERT
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_MULTIUSER
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_PRINTK
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_DEVTMPFS
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_PROC_FS
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_SYSFS
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_DEVTMPFS_MOUNT
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_TMPFS
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_TTY
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_UNIX98_PTYS
${COOKBOOK_SOURCE}/scripts/config --disable CONFIG_LEGACY_PTYS
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_BINFMT_ELF
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_BINFMT_SCRIPT
# display
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_VT
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_VT_CONSOLE
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_VGA_CONSOLE
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_SERIAL_8250
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_SERIAL_8250_CONSOLE
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_EARLY_PRINTK
# network
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_NET
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_UNIX
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_INET
# kvm
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_PARAVIRT
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_KVM_GUEST
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_KVM_CLOCK
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_VIRTIO
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_VIRTIO_MENU
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_VIRTIO_PCI
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_VIRTIO_MMIO
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_VIRTIO_BLK
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_VIRTIO_NET
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_VIRTIO_CONSOLE
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_HW_RANDOM_VIRTIO
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_NET_9P
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_NET_9P_VIRTIO
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_9P_FS
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_ACPI
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_POWER_RESET

make "HOSTCFLAGS=-I${COOKBOOK_TOOLCHAIN}/include" HOSTLDFLAGS="-L${COOKBOOK_TOOLCHAIN}/lib" -j$COOKBOOK_MAKE_JOBS < /dev/null
mkdir -p $COOKBOOK_STAGE/boot
cp -v arch/x86/boot/bzImage $COOKBOOK_STAGE/boot
"""
