#TODO not compiled or tested
[source]
tar = "https://cdn.kernel.org/pub/linux/kernel/v7.x/linux-7.0.3.tar.xz"
blake3 = "d9b0776504d3b1f03bdd4ce638110a4070a4dabed57fcc83e4940e9bbf7cbc0b"

[build]
template = "custom"
dev-dependencies = [
    "host:elfutils",
    "host:bc",
]
script = """
pushd "$COOKBOOK_SOURCE"
make "O=$COOKBOOK_BUILD" tinyconfig
popd

export KBUILD_OUTPUT=$COOKBOOK_BUILD
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_64BIT
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_BLK_DEV_INITRD
${COOKBOOK_SOURCE}/scripts/config --disable CONFIG_RD_GZIP
${COOKBOOK_SOURCE}/scripts/config --disable CONFIG_RD_BZIP2
${COOKBOOK_SOURCE}/scripts/config --disable CONFIG_RD_LZMA
${COOKBOOK_SOURCE}/scripts/config --disable CONFIG_RD_XZ
${COOKBOOK_SOURCE}/scripts/config --disable CONFIG_RD_LZO
${COOKBOOK_SOURCE}/scripts/config --disable CONFIG_RD_LZ4
${COOKBOOK_SOURCE}/scripts/config --disable CONFIG_RD_ZSTD
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_EXPERT
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_MULTIUSER
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_PRINTK
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_DEVTMPFS
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_TTY
${COOKBOOK_SOURCE}/scripts/config --disable CONFIG_UNIX98_PTYS
${COOKBOOK_SOURCE}/scripts/config --disable CONFIG_LEGACY_PTYS
${COOKBOOK_SOURCE}/scripts/config --enable CONFIG_BINFMT_ELF

make "HOSTCFLAGS=-I${COOKBOOK_TOOLCHAIN}/include" HOSTLDFLAGS="-L${COOKBOOK_TOOLCHAIN}/lib" -j$COOKBOOK_MAKE_JOBS < /dev/null
cp -v arch/x86/boot/bzImage $COOKBOOK_STAGE/
"""
