[source]
tar = "https://github.com/fragglet/sdl-sopwith/releases/download/sdl-sopwith-2.9.0/sdl-sopwith-2.9.0.tar.gz"
blake3 = "f06a6d0c826b42989c58074f85ed8e19fbfd5fe53a357ba356bc1109bcf91ef3"
script = """
DYNAMIC_INIT
autotools_recursive_regenerate
"""

[build]
template = "custom"
dependencies = [
    "sdl2",
    "liborbital",
    "libiconv",
]
dev-dependencies = [
    "libstdcxx"
]
script = """
DYNAMIC_INIT

# For some reason, cook_configure breaks spectacularly on this
# We will just copy instead
rsync -av --delete "${COOKBOOK_SOURCE}/" ./
COOKBOOK_CONFIGURE="./configure"
COOKBOOK_CONFIGURE_FLAGS+=(
    --with-sdl-prefix="${COOKBOOK_SYSROOT}"
)
cookbook_configure
"""
