#TODO compiled but not tested
[source]
git = "https://github.com/flukejones/room4doom"
shallow_clone = true
[build]
template = "cargo"
cargopackages = ["room4doom"]
dependencies = [
    "sdl2",
    "sdl2-mixer"
]
