#TODO compile and test
#TODO add command to install
[source]
git = "https://github.com/rafaelcn/pong-game"
rev = "6120b8b50d895fd2496d02e4fa41abdaadd2d897"
shallow_clone = true
[build]
template = "custom"
dependencies = [
    "sdl2",
    "sdl2-image",
    "sdl2-ttf",
]
script = """
rsync -av --delete "${COOKBOOK_SOURCE}/" ./
DYNAMIC_INIT
"${COOKBOOK_MAKE}" -j "${COOKBOOK_MAKE_JOBS}"
"""
