#TODO missing syscall function
[source]
tar = "https://gitlab.torproject.org/tpo/core/torsocks/-/archive/v2.5.0/torsocks-v2.5.0.tar.bz2"
script = """
autotools_recursive_regenerate
"""
[build]
template = "configure"
