[source]
git = "https://gitlab.redox-os.org/Ibuki.O/relibc.git"
branch = "namespace-improvement"

[build]
template = "custom"
script = """
export CARGO=${CARGO:-env -u CARGO cargo}
"${COOKBOOK_MAKE}" \
    -C "${COOKBOOK_SOURCE}" \
    -j"$($NPROC)" \
    DESTDIR="${COOKBOOK_STAGE}/usr" \
    install
"""
