#TODO compiled but not tested (after a camino crate patch)
[source]
git = "https://github.com/trailofbits/cargo-unmaintained"
shallow_clone = true
[build]
template = "cargo"
dependencies = [
    "openssl3",
]
