#TODO missing script for gnu make: https://github.com/mawww/kakoune#getting-started
[source]
tar = "https://github.com/mawww/kakoune/releases/download/v2026.04.12/kakoune-2026.04.12.tar.bz2"
[build]
template = "custom"
