#TODO add kf6 dependencies: https://invent.kde.org/games/kubrick/-/blob/master/CMakeLists.txt?ref_type=heads#L36
[source]
git = "https://invent.kde.org/games/kubrick"
rev = "v26.04.3"
shallow_clone = true
[build]
template = "cmake"
dev-dependencies = ["host:ecm"]
dependencies = [
    "qt6-base",
    "libkdegames",
]
