#TODO linking errors
[source]
git = "https://github.com/fabiangreffrath/crispy-doom"
rev = "crispy-doom-7.1"
shallow_clone = true
[build]
template = "cmake"
cmakeflags = [
    "-DENABLE_SDL2_NET=OFF",
    "-DENABLE_SDL2_MIXER=OFF",
]
dependencies = [
    "sdl2",
    #"sdl2-mixer",
    #"sdl2-net",
]
