#TODO not compiled or tested
#TODO discover minimum dependencies from cmake log
[source]
git = "https://invent.kde.org/games/kpat"
rev = "v26.04.3"
shallow_clone = true
[build]
template = "cmake"
cmakeflags = [
    "-DBUILD_DOC=OFF",
]
dev-dependencies = ["host:ecm"]
dependencies = [
    "qt6-base",
    "libkdegames",
]
