#TODO compile and test
[source]
git = "https://github.com/KhronosGroup/SPIRV-Cross"
rev = "vulkan-sdk-1.4.350.0"
shallow_clone = true
[build]
template = "cmake"
cmakeflags = [
    "-DSPIRV_CROSS_ENABLE_TESTS=OFF"
]
