#TODO "unsupported platform" error
#TODO need to be built with clang for best performance
# build instructions: https://pcsx2.net/docs/advanced/building#building-on-linux
[source]
git = "https://github.com/PCSX2/pcsx2"
rev = "v2.6.3"
shallow_clone = true
[build]
template = "cmake"
cmakeflags = [
    "-DCMAKE_CXX_COMPILER_LAUNCHER=ccache",
    "-DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON",
    "-DENABLE_TESTS=OFF",
    #"-DLTO_PCSX2_CORE=ON", # disabled to speedup testing
    "-DPACKAGE_MODE=ON",
    "-DUSE_OPENGL=OFF",
    "-DUSE_VULKAN=OFF",
    "-DX11_API=OFF",
    "-DWAYLAND_API=OFF",
    "-DUSE_BACKTRACE=OFF",
    "-DENABLE_QT_UI=OFF",
    "-DENABLE_GSRUNNER=ON",
]
# dependencies = [
#     "sdl3",
#     "xz",
#     "libpng",
#     "qt6-base",
#     "qt6-svg",
#     "mesa",
#     "libaio",
#     "harfbuzz",
#     "libpcap",
#     "pipewire",
#     "libsamplerate",
#     "soundtouch",
#     "zlib",
#     "libxml2",
#     "ffmpeg6",
# ]
