#TODO Not compiled or tested
#TODO determine what llvm variant is needed
[source]
git = "https://github.com/drahnr/cargo-spellcheck"
shallow_clone = true
[build]
template = "cargo"
#dependencies = [
#    "llvm21",
#    "llvm21.runtime",
#]
