# server variant meta-package
[package]
dependencies = [
    "sys",
    "bash",
    "bottom",
    "ca-certificates",
    #"contain",
    "curl",
    "diffutils",
    "extrautils",
    "findutils",
    "git",
    "installer",
    "ion",
    "kibi",
    "uutils-procps",
]
description = "Server components"
