#TODO need testing
[source]
tar = "https://sqlite.org/2025/sqlite-autoconf-3490200.tar.gz"
blake3 = "96e071dc4f964311882334e927f017d8383915b1b140adcf308957dff213aa8c"
script = """
autotools_recursive_regenerate
"""
[build]
template = "custom"
script = """
DYNAMIC_INIT
# don't limit the malloc, we'll use in memory a lot
export CPPFLAGS="$CPPFLAGS -DSQLITE_MALLOC_SOFT_LIMIT=0"
# remapping doesn't work (crashing firefox at startup)
export CPPFLAGS="$CPPFLAGS -DSQLITE_MAX_MMAP_SIZE=0"
# redoxfs has race condition issues
export CPPFLAGS="$CPPFLAGS -DSQLITE_THREADSAFE=1"
# our /tmp is slow
export CPPFLAGS="$CPPFLAGS -DSQLITE_TEMP_STORE=3"
cookbook_configure
"""
