#TODO not compiled or tested
[source]
git = "https://github.com/ccbrown/iocraft"
shallow_clone = true
[build]
template = "cargo"
cargoexamples = [
    "borders",
    "calculator",
    "counter",
    "fullscreen",
    "hello_world",
    "overlap",
    "progress_bar",
    "scrolling",
    "table",
    "use_input",
    "use_output",
    "weather",
]
