[source]
same_as = "../base"

[build]
template = "custom"
dependencies = [
  "redoxfs",
]
script = """
cd "${COOKBOOK_SOURCE}" && make install-initfs \
    SRC_DIR="${COOKBOOK_SOURCE}" SYSROOT="${COOKBOOK_SYSROOT}" \
    LINKER="${GNU_TARGET}-ld" CARGO="${COOKBOOK_CARGO}" \
    BUILD_DIR="${COOKBOOK_BUILD}" DESTDIR="${COOKBOOK_STAGE}"
"""
