[source]
same_as = "../base"

[build]
template = "custom"
dependencies = [
  "redoxfs",
]
script = """
BINS=(
    init
    logd
    ramfs
    randd
    zerod

    acpid
    fbbootlogd
    fbcond
    hwd
    inputd
    lived
    nvmed
    pcid
    pcid-spawner
    rtcd
    vesad
    virtio-blkd
    virtio-gpud
)

aarch64_bins()
{
    case "${BOARD}" in
        raspi3b*)
            BINS+=(bcm2835-sdhcid)
        ;;
        *)
        ;;
    esac
}

case "${TARGET}" in
    i586-unknown-redox | i686-unknown-redox | x86_64-unknown-redox)
        BINS+=(ahcid ided ps2d)
        ;;
    aarch64-unknown-redox)
        aarch64_bins
        ;;
    *)
        ;;
esac

rm -rf "${COOKBOOK_BUILD}/initfs"

# Copy config files
mkdir -p "${COOKBOOK_BUILD}/initfs/lib/init.d" "${COOKBOOK_BUILD}/initfs/lib/pcid.d"
cp "${COOKBOOK_SOURCE}/init.initfs.d"/* "${COOKBOOK_BUILD}/initfs/lib/init.d/"
cp "${COOKBOOK_SOURCE}/drivers/initfs.toml" "${COOKBOOK_BUILD}/initfs/lib/pcid.d/initfs.toml"

# Build daemons and drivers
CARGO_PROFILE_RELEASE_OPT_LEVEL=s CARGO_PROFILE_RELEASE_PANIC=abort \
    "${COOKBOOK_CARGO}" build ${build_flags} \
    --manifest-path "${COOKBOOK_SOURCE}/Cargo.toml" \
    $(for bin in "${BINS[@]}"; do echo "-p" "${bin}"; done)

mkdir -pv "${COOKBOOK_BUILD}/initfs/bin" "${COOKBOOK_BUILD}/initfs/lib/drivers"
for bin in "${BINS[@]}"
do
    case "${bin}" in
      init | logd | ramfs | randd | zerod | pcid | pcid-spawner | fbbootlogd | fbcond | inputd | vesad | lived | ps2d | acpid | bcm2835-sdhcid | rtcd | hwd)
        cp -v "target/${TARGET}/${build_type}/${bin}" "${COOKBOOK_BUILD}/initfs/bin"
        ;;
      *)
        cp -v "target/${TARGET}/${build_type}/${bin}" "${COOKBOOK_BUILD}/initfs/lib/drivers"
        ;;
    esac
done

cp "${COOKBOOK_SYSROOT}/usr/bin/redoxfs" "${COOKBOOK_BUILD}/initfs/bin"

# Build bootstrap
ARCH="$(echo "${GNU_TARGET}" | cut -d - -f1)"
(cd "${COOKBOOK_SOURCE}/bootstrap" && "${COOKBOOK_CARGO}" rustc \
    --release -- -Ctarget-feature=+crt-static -Clinker="${GNU_TARGET}-ld")
cp "${COOKBOOK_BUILD}/target/${TARGET}/release/bootstrap" "${COOKBOOK_BUILD}/bootstrap"

# Assemble initfs
env -u CARGO -u RUSTFLAGS cargo run --manifest-path "${COOKBOOK_SOURCE}/initfs/tools/Cargo.toml" --bin redox-initfs-ar -- "${COOKBOOK_BUILD}/initfs" "${COOKBOOK_BUILD}/bootstrap" -o "${COOKBOOK_BUILD}/initfs.img"
mkdir -pv "${COOKBOOK_STAGE}/usr/lib/boot"
cp "${COOKBOOK_BUILD}/initfs.img" "${COOKBOOK_STAGE}/usr/lib/boot/initfs"
"""
