[source]
git = "https://github.com/luarocks/luarocks.git"
shallow_clone = true
[build]
template = "custom"
dependencies = [
"lua54"
]
script = """
DYNAMIC_INIT
COOKBOOK_CONFIGURE_FLAGS=(
    --prefix=/usr
    --sysconfdir=/etc
    --with-lua-include=$COOKBOOK_SYSROOT/include
    --with-lua-bin=$COOKBOOK_SYSROOT/bin
    --with-lua-lib=$COOKBOOK_SYSROOT/lib
)
cd "${COOKBOOK_SOURCE}"
cookbook_configure
"""
