#TODO: fails to link libcrypto.so
[source]
git = "https://github.com/veeso/pavao.git"

[build]
template = "cargo"
dependencies = [
    "openssl3"
]
cargoflags = [
    "--features vendored"
]
cargoexamples = [
    "tree"
]
