#TODO missing script for gnu make
# build instructions: https://github.com/jarun/bcal#installation
[source]
tar = "https://github.com/jarun/bcal/releases/download/v2.5/bcal-v2.5.tar.gz"
[build]
template = "custom"
dependencies = [
    "readline",
]
