#TODO cargo-util crate error
[source]
git = "https://github.com/JanLikar/cargo-clone"
shallow_clone = true
[build]
template = "cargo"
cargopackages = ["cargo-clone"]
dependencies = [
    "openssl3",
]
