#TODO not compiled or tested
# build instructions: https://github.com/mummer4/mummer/blob/master/INSTALL.md
[source]
tar = "https://github.com/mummer4/mummer/releases/download/v4.0.1/mummer-4.0.1.tar.gz"
[build]
template = "configure"
