#TODO not compiled or tested
# build instructions: https://wiki.hyprland.org/Getting-Started/Installation/#cmake-recommended
[source]
tar = "https://github.com/hyprwm/Hyprland/releases/download/v0.55.4/source-v0.55.4.tar.gz"
[build]
template = "custom"
dependencies = [
    "libinput",
    "libxkbcommon",
    "libxcb",
    "pango",
    "cairo",
    "pixman",
    "libwayland",
    "seatd",
    "libxrender",
    "libx11",
    "libxcomposite",
    "libxfixes",
]
script = """
DYNAMIC_INIT
COOKBOOK_CMAKE_FLAGS+=(
    -DNO_SYSTEMD=ON
)
cookbook_cmake
mkdir -pv "${COOKBOOK_STAGE}"/usr/share/wayland-sessions
cp -rv "${COOKBOOK_SOURCE}"/example/hyprland.desktop "${COOKBOOK_STAGE}"/usr/share/wayland-sessions
"""
