#TODO write a script for proper packaging
# use the "uv run mitmproxy --version" command to run
# installation instructions: https://github.com/mitmproxy/mitmproxy/blob/main/CONTRIBUTING.md
[source]
tar = "https://downloads.mitmproxy.org/12.2.3/mitmproxy-12.2.3.tar.gz"
[build]
template = "custom"
script = """
mkdir -pv "${COOKBOOK_STAGE}/home/user/mitmproxy"
cp -rv "${COOKBOOK_SOURCE}"/* "${COOKBOOK_STAGE}/home/user/mitmproxy"
"""
