[source]
git = "https://gitlab.redox-os.org/redox-os/glutin.git"
branch = "redox-0.30"
upstream = "https://github.com/rust-windowing/glutin.git"

[build]
template = "custom"
cargopath = "glutin_examples"
dependencies = [
    "mesa",
    "zlib"
]
script = """
DYNAMIC_INIT
CARGOPATH="glutin_examples" cookbook_cargo_examples window
"""
