[source]
git = "https://gitlab.redox-os.org/redox-os/glutin.git"
branch = "redox-0.30"
upstream = "https://github.com/rust-windowing/glutin.git"

[build]
template = "custom"
dependencies = [
    "mesa",
    "zlib",
]
dev-dependencies = [
    "libstdcxx",
]
script = """
DYNAMIC_INIT
COOKBOOK_CARGO_FLAGS=()
CARGOPATH="glutin_examples"
export RUSTFLAGS="$RUSTFLAGS -Clink-arg=-lOSMesa"
cookbook_cargo_examples window
"""
