#TODO compiles, fails to run: termbox crate: Termbox::init() function
[source]
git = "https://github.com/osa1/tiny"
shallow_clone = true
[build]
template = "custom"
script = """
DYNAMIC_INIT
cookbook_cargo_packages tiny
"""
