#TODO compile and test
# build instructions: https://docs.zeek.org/en/v8.0.8/building-from-source.html
[source]
tar = "https://download.zeek.org/zeek-8.0.8.tar.gz"
[build]
template = "configure"
dependencies = [
    "libpcap",
    "openssl3",
    "zlib",
]
