#TODO build the userspace implementation: https://github.com/andreas-abel/nanoBench#user-space-version
[source]
git = "https://github.com/andreas-abel/nanoBench"
rev = "36c077fd30db11e8c83cedfcb58daa505d1d0b12"
shallow_clone = true
[build]
template = "custom"
[package]
dependencies = [
    "python312",
]
