#TODO linking error
[source]
git = "https://github.com/j-g00da/mousefood"
shallow_clone = true
[build]
template = "cargo"
cargopackageprefixed = true
cargopackages = ["simulator"]
dependencies = ["sdl2"]
