#TODO discover minimum dependencies from meson log
# build instructions: https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/gnome-49/docs/building-and-running.md
[source]
tar = "https://download.gnome.org/sources/gnome-shell/49/gnome-shell-49.7.tar.xz"
[build]
template = "meson"
mesonflags = [
    "-Dcamera_monitor=false",
    "-Dextensions_tool=false",
    "-Dextensions_app=false",
    "-Dman=false",
    "-Dtests=false",
    "-Dnetworkmanager=false",
    "-Dportal_helper=false",
    "-Dsystemd=false",
]
