#TODO not compiled or tested
[source]
tar = "https://download.gnome.org/sources/showtime/49/showtime-49.1.tar.xz"
[build]
template = "meson"
dependencies = [
    "gtk4",
    "libadwaita",
]
dev-dependencies = ["blueprint"]
