[source]
tar = "https://ftp.gnu.org/gnu/bash/bash-5.3.tar.gz"

[build]
template = "custom"
dependencies = [
    "readline",
]
script = """
DYNAMIC_INIT
COOKBOOK_CONFIGURE_FLAGS+=(
    bash_cv_func_sigsetjmp=no
    ac_cv_func_getrlimit=no
    ac_cv_func_dlopen=no
    ac_cv_func_dlclose=no
    bash_cv_getenv_redef=no
    --with-bash-malloc=no
    --with-installed-readline=yes
)
cookbook_configure
ln -s "bash" "${COOKBOOK_STAGE}/usr/bin/sh"
cp -r "${COOKBOOK_RECIPE}/etc" "${COOKBOOK_STAGE}/etc"
"""
