# The Redox build server configuration

# General settings
[general]
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]

# If you need to disable some broken package comment out instead of removal to not increase the maintenance cost
#TODO: commented out recipes need to be built and tested inside of Redox to verify if they returned to work

# Meta-packages below

auto-test = {}
autotools = {}
dev-essential = {}
dev-redox = {}
llvm21-common = {}
mate-common = {}
redox-tests = {}
x11-minimal = {}
x11-full = {}

# Normal packages below

acid = {}
adwaita-icon-theme = {}
atk = {}
autoconf = {}
automake = {}
base = {}
bash = {}
bash-completion = {}
binutils = {}
bootloader = {}
bottom = {}
bzip2 = {}
ca-certificates = {}
cairo = {}
cairo-demo = {}
cbindgen = {}
classicube = {}
cleye = {}
cmake = {}
cmatrix = {}
composer = {}
contain = {}
coreutils = {}
cosmic-edit = {}
cosmic-files = {}
cosmic-icons = {}
cosmic-reader = {}
cosmic-term = {}
cosmic-text = {}
cpal = {}
curl = {}
dash = {}
dejavu = {}
devilutionx = {}
diffutils = {}
dosbox = {}
duktape = {}
eduke32 = {}
exampled = {}
expat = {}
extrautils = {}
ffmpeg6 = {}
file = {}
findutils = {}
fish-shell = {}
flycast = {}
fontconfig = {}
freeciv = {}
freedoom = {}
freefont = {}
freepats = {}
freetype2 = {}
fribidi = {}
gawk = {}
gcc13 = {}
gdbserver = {}
gdk-pixbuf = {}
gears = {}
generaluser-gs = {}
gettext = {}
gigalomania = {}
git = {}
glib = {}
glutin = {}
gnu-binutils = {}
gnu-grep = {}
gnu-make = {}
goaccess = {}
gstreamer = {}
harfbuzz = {}
hicolor-icon-theme = {}
helix = {}
hello-redox = {}
hf = {}
htop = {}
jansson = {}
jq = {}
installer = {}
installer-gui = {}
intel-one-mono = {}
ion = {}
kernel = {}
kibi = {}
lci = {}
libarchive = {}
libatomic = {}
libavif = {}
libc-bench = {}
libedit = {}
libffi = {}
libflac = {}
libgcc = {}
libgmp = {}
libiconv = {}
libicu = {}
libjpeg = {}
libmodplug1 = {}
libmpfr = {}
libnettle = {}
libogg = {}
libonig = {}
liborbital = {}
libpsl = {}
libpng = {}
libsodium = {}
libssh2 = {}
libstdcxx = {}
libtool = {}
libuuid = {}
liburcu = {}
libuv = {}
libvorbis = {}
libwebp = {}
libxkbcommon = {}
libxcursor = {}
libxml2 = {}
llvm21 = {}
lsd = {}
lua54 = {}
lua-compat-53 = {}
luajit = {}
luarocks = {}
lz4 = {}
mednafen = {}
mesa = {}
mesa-glu = {}
mesa-demos-x11 = {}
mgba = {}
mpc = {}
nano = {}
nasm = {}
ncdu = {}
ncurses = {}
ncursesw = {}
neovim = {}
netdb = {}
netsurf = {}
netutils = {}
neverball = {}
nghttp2 = {}
nginx = {}
nodejs-21 = {}
nushell = {}
onefetch = {}
openjazz = {}
openjk = {}
openssh = {}
openssl1 = {}
openssl3 = {}
openttd = {}
openttd-opengfx = {}
openttd-openmsx = {}
openttd-opensfx = {}
opentyrian = {}
orbclient = {}
orbdata = {}
orbital = {}
orbterm = {}
orbutils = {}
os-test-bins = {}
osdemo = {}
pango = {}
patch = {}
patchelf = {}
pcre = {}
pcre2 = {}
perg = {}
periodictable = {}
perl5 = {}
php84 = {}
pixelcannon = {}
pixman = {}
pkg-config = {}
pkgar = {}
pkgutils = {}
pls = {}
pop-icon-theme = {}
powerline = {}
prboom = {}
procedural-wallpapers-rs = {}
python312 = {}
quakespasm = {}
readline = {}
redox-fatfs = {}
redox-games = {}
redoxfs = {}
relibc = {}
relibc-tests = {}
relibc-tests-bins = {}
ripgrep = {}
rodioplay = {}
rs-nes = {}
rsync = {}
rust = {}
rust64 = {}
rustpython = {}
rustual-boy = {}
rvvm = {}
scummvm = {}
sdl-gfx = {}
sdl1 = {}
sdl1-image = {}
sdl1-mixer = {}
sdl1-ttf = {}
sdl2 = {}
sdl2-gears = {}
sdl2-image = {}
sdl2-mixer = {}
sdl2-ttf = {}
sed = {}
servo = {}
shared-mime-info = {}
shellharden = {}
shellstorm = {}
simple-http-server = {}
smallvil = {}
smith = {}
sodium = {}
softbuffer-wayland = {}
sopwith = {}
sqlite3 = {}
strace = {}
syobonaction = {}
terminfo = {}
timidity = {}
tmux = {}
tokei = {}
ttf-hack = {}
userutils = {}
uutils = {}
uutils-procps = {}
vim = {}
vttest = {}
wasmtime = {}
wayland-rs = {}
webkitgtk3 = {}
wget = {}
winit = {}
winit-wayland = {}
xxhash = {}
xz = {}
zenity = {}
zoxide = {}
zsh = {}
zlib = {}
zstd = {}

#benchmarks = {}
#binutils-gdb = {}
#book = {}
#cookbook = {}
#cosmic-settings = {}
#cosmic-store = {}
#dynamic-example = {}
#fal
#fd = {} # ctrlc-3.1.1
#freeglut = {}
#friar = {} # mio patch
#game-2048 = {} # rustc-serialize
#gitoxide = {} # needs -fPIC
#hematite = {} # needs crate patches for redox-unix
#ibm-plex = {}
#iced = {}
#libcosmic = {}
#mdp = {} # gcc hangs
#miniserve = {} # libc ifaddrs
#mupen64plus = {}
#noto-color-emoji = {}
#orbcalculator = {}
#ostest-bins = {}
#pastel = {} # needs crate patches for redox-unix
#pathfinder = {} # servo-fontconfig
#pciids = {}
#pop-wallpapers = {}
#qemu = {} # can be built, but not working
#retroarch = {} # cannot locate GL
#rust-cairo = {} # linking errors
#rust-cairo-demo = {} # linking errors
#schismtracker = {} # uses system includes
#sdl-player = {} # wctype_t
#sdl2-gfx = {}
#twin-commander = {}
#ubuntu-wallpapers = {}
#vice = {} # linker errors
#vvvvvv = {} # did not compile
#webrender = {} # unwind
#website = {}
#wesnoth = {}
