# Base configuration for linux

# General settings
[general]
# Do not prompt if settings are not defined
prompt = false

[packages]
linux-base = {}
relibc = {}
# kernel don't need to be included in image, but needed in the build loop
linux-kernel = {}

[[files]]
path = "/dev"
data = ""
directory = true
mode = 0o755

[[files]]
path = "/proc"
data = ""
directory = true
mode = 0o755

[[files]]
path = "/sys"
data = ""
directory = true
mode = 0o755

[[files]]
path = "/tmp"
data = ""
directory = true
mode = 0o755

[[files]]
path = "/root"
data = ""
directory = true
mode = 0o755

[[files]]
path = "/run"
data = ""
directory = true
mode = 0o755

[[files]]
path = "/mnt"
data = ""
directory = true
mode = 0o755

[[files]]
path = "/etc/os-release"
data = "../usr/lib/os-release"
symlink = true

# https://www.freedesktop.org/software/systemd/man/latest/os-release.html
[[files]]
path = "/usr/lib/os-release"
data = """
PRETTY_NAME="Linux Relibc OS"
NAME="Linux Relibc OS"
VERSION_ID="0.9.0"
VERSION="0.9.0"
ID="relibc-os"

HOME_URL="https://redox-os.org/"
DOCUMENTATION_URL="https://redox-os.org/docs/"
SUPPORT_URL="https://redox-os.org/community/"
"""
