#TODO missing script for gnu make: https://github.com/finalburnneo/FBNeo/blob/master/README-SDL.md#sdl2
[source]
git = "https://github.com/finalburnneo/FBNeo"
rev = "a50ddd24dcd7bed4b625eeea9b25631072bbfe80"
shallow_clone = true
[build]
template = "custom"
dependencies = [
    "sdl2",
    "sdl2-image",
]
