#TODO x11rb and rustic crate errors
[source]
git = "https://github.com/HactarCE/Hyperspeedcube"
branch = "v1"
shallow_clone = true
[build]
template = "cargo"
cargopackages = ["hyperspeedcube"]
#dependencies = [ # needed?
 #   "glib",
 #   "gtk3",
 #   "atk",
 #   "libxkbcommon",
#]
