#TODO compile and test
# installation instructions: https://cgit.git.savannah.gnu.org/cgit/tiger.git/tree/USING#n80
[source]
tar = "https://download.savannah.gnu.org/releases/tiger/tiger_3.2.4rc1.tar.gz"
[build]
template = "configure"
[package]
dependencies = [
    "bash"
]
