[source]
tar = "https://www.x.org/releases/individual/xserver/xorg-server-21.1.16.tar.xz"
blake3 = "b47c68a0a8bc5b69143d95440fbf75c17245ba8bc2c28a8d9619d8c6890dca58"
patches = ["redox.patch"]

[build]
dependencies = [
    "font-util",
    "freetype2",
    "libfontenc",
    "libpng",
    "libpthread-stubs",
    #TODO: used for secure-rpc, needs syslog: "libtirpc",
    "libx11",
    "libxau",
    "libxcb",
    "libxcvt",
    "libxdmcp",
    "libxext",
    "libxfixes",
    "libxfont2",
    "libxkbfile",
    "libxxf86vm",
    "mesa-x11",
    "openssl3",
    "pixman",
    "xkbcomp",
    "x11proto",
    "xtrans",
    "zlib",
]
template = "custom"
script = """
DYNAMIC_INIT

if [ "${COOKBOOK_DYNAMIC}" != "1" ]; then
    COOKBOOK_MESON_FLAGS+=(-Dglx=false -Dxnest=false)
fi

cookbook_meson \
    -Ddri1=false \
    -Dglamor=false \
    -Dint10=false \
    -Dpciaccess=false \
    -Dsecure-rpc=false \
    -Dudev=false \
    -Dudev_kms=false \
    -Dvgahw=false \
    -Dxres=false \
    -Dxvfb=false \
    -Dxkb_dir=/usr/share/X11/xkb \
    -Dxkb_bin_dir=/usr/bin
"""
