#TODO not compiled or tested
# build instructions: https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md
[source]
tar = "https://bitcoincore.org/bin/bitcoin-core-30.2/bitcoin-30.2.tar.gz"
[build]
template = "cmake"
cmakeflags = [
    "-DENABLE_WALLET=OFF",
    "-DENABLE_IPC=OFF",
    "-DBUILD_TESTS=OFF",
    "-DINSTALL_MAN=OFF",
]
dependencies = [
    "boost",
    "libevent",
]
