# source is part of cookbook

[build]
dependencies = [
    "cairo",
    "expat",
    "fontconfig",
    "freetype2",
    "liborbital",
    "libpng",
    "pixman",
    "zlib",
]
template = "custom"
script = """
DYNAMIC_INIT
${CXX} ${CPPFLAGS} ${LDFLAGS} \
    "${COOKBOOK_RECIPE}/cairo-demo.c" \
    -o cairo-demo \
    -lorbital $("${PKG_CONFIG}" --libs cairo)

mkdir -pv "${COOKBOOK_STAGE}/bin"
cp -v "cairo-demo" "${COOKBOOK_STAGE}/bin/cairo-demo"
"""
