#TODO not compiled or tested
[source]
git = "https://github.com/copper-project/copper-rs"
shallow_clone = true
[build]
template = "cargo"
cargopackages = [
    "cu-rp-balancebot",
    "cu-flight-controller",
]
