#TODO not compiled or tested
# build instructions: https://specfem2d.readthedocs.io/en/latest/02_getting_started/
[source]
git = "https://github.com/SPECFEM/specfem2d"
rev = "v8.1.0"
shallow_clone = true
[build]
template = "configure"
configureflags = [
    "FC=gfortran"
]
