#TODO not compiled or tested
#TODO discover minimum dependencies from cmake log
[source]
git = "https://invent.kde.org/utilities/skanpage"
rev = "v26.04.3"
shallow_clone = true
[build]
template = "cmake"
cmakeflags = ["--preset=release"]
dependencies = [
    "sane-backends",
]
